### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by lucastabelini** [lucastabelini/LaneATT#1]
The code will be published soon. Subscribe to this issue to be notified when that happens.

**Comment by x2ss** [comment]
thanks for sharing！

All the best.

**Comment by ztjsw** [comment]
When will the code be published?

**Comment by lucastabelini** [comment]
I'm still not authorized to share it yet. It will take a little bit longer. What I can tell you is that the code largely follows the same structure of [PolyLaneNet](https://github.com/lucastabelini/PolyLaneNet). If you want to know something specific or have further questions, feel free to open a new issue or send me an e-mail.

**Comment by SoulmateB** [comment]
When will the code be published?

**Comment by lucastabelini** [comment]
The source code has been published.
