### ISSUE TITLE
[Error Report] dfitpack.error: (1<=k && k<=5) failed for 3rd argument k: fpcurf0:k=0

### ISSUE THREAD

**Issue by thlin002** [lucastabelini/LaneATT#10]
I ran the program with the command "$ python main.py test --exp_name laneatt_r34_tusimple --view all" and pressed a key to go through all the result images, but an error occurs when it progressed to the 2417th result (87%) every time. 

If I run the command "$ python main.py test --exp_name laneatt_r34_tusimple/" without flag "--view all", the program could run successfully.

Does this issue occur to anyone? How should I solve it? Thanks!

```
$ python main.py test --exp_name laneatt_r34_tusimple --view all
[2020-12-19 10:14:25,366] [lib.runner] [INFO] Loading model experiments/laneatt_r34_tusimple/models/model_0100.pt
[2020-12-19 10:14:34,055] [lib.datasets.tusimple] [INFO] Loading TuSimple annotations...
[2020-12-19 10:14:34,670] [lib.datasets.tusimple] [INFO] 2782 annotations loaded, with a maximum of 5 lanes in an image.
[2020-12-19 10:14:34,671] [lib.datasets.lane_dataset] [INFO] Transforming annotations to the model's target format...
[2020-12-19 10:14:45,315] [lib.datasets.lane_dataset] [INFO] Done.
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 2417/2782 [08:38<01:14,  4.89it/s]
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 55, in main
    runner.eval(epoch=args.epoch or exp.get_last_checkpoint_epoch(), save_predictions=args.save_predictions)
  File "/home/thlin/Code/CSIE_Project/LaneATT/lib/runner.py", line 97, in eval
    img, fp, fn = dataloader.dataset.draw_annotation(idx, img=img, pred=prediction[0])
  File "/home/thlin/Code/CSIE_Project/LaneATT/lib/datasets/lane_dataset.py", line 191, in draw_annotation
    label = self.label_to_lanes(label)
  File "/home/thlin/Code/CSIE_Project/LaneATT/lib/datasets/lane_dataset.py", line 176, in label_to_lanes
    lanes.append(Lane(points=points))
  File "/home/thlin/Code/CSIE_Project/LaneATT/lib/lane.py", line 10, in __init__
    self.function = InterpolatedUnivariateSpline(points[:, 1], points[:, 0], k=min(3, len(points) - 1))
  File "/home/thlin/.venv/LaneATT-env/lib/python3.8/site-packages/scipy/interpolate/fitpack2.py", line 611, in __init__
    self._data = dfitpack.fpcurf0(x, y, k, w=w, xb=bbox[0],
dfitpack.error: (1<=k && k<=5) failed for 3rd argument k: fpcurf0:k=0
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 2417/2782 [08:38<01:18,  4.66it/s]
```

**Comment by lucastabelini** [comment]
I was able to reproduce the issue and it seems to occur on a ground-truth lane with only 2 annotated points. For some reason, after a few format conversions, only one point remains. Thus, the spline interpolation is impossible. I'll have to look into it a bit deeper to find out the reason for that, but it probably has no impact on other stuff, since that part of the code is only ran when visualizing labels.

**Comment by thlin002** [comment]
Okay, Got it. Thank you for looking into this issue!

**Comment by jiamingZhong93** [comment]
Hi lucastabelini @lucastabelini ,

I got the same issue when generating videos:

My command: (I previously generated the file predictions.pkl)
run utils/gen_video.py --pred predictions.pkl --cfg experiments/laneatt_r34_tusimple/config.yaml --out tusimple34.avi

![image](https://user-images.githubusercontent.com/90985019/144689495-48936f7b-34d3-4d5b-a5de-6b9b5ecca178.png)

It will always happen at 87%

It will also happen when using the culane dataset.

**Comment by zhangzhongyuan1996** [comment]
how to deal the poblem？I can not see the answer.Anyone tell me ?

**Comment by zhangzhongyuan1996** [comment]
> I was able to reproduce the issue and it seems to occur on a ground-truth lane with only 2 annotated points. For some reason, after a few format conversions, only one point remains. Thus, the spline interpolation is impossible. I'll have to look into it a bit deeper to find out the reason for that, but it probably has no impact on other stuff, since that part of the code is only ran when visualizing labels.

have you found the truth?I still have this problem

**Comment by 0nea** [comment]
> how to deal the poblem？I can not see the answer.Anyone tell me ?

do you solve it? I still have this problem

**Comment by zhangzhongyuan1996** [comment]
Yes，maybe you should check every step you think important,you can use "print" to check these messages.发自我的 iPhone在 2024年3月14日，22:10，0nea ***@***.***> 写道：﻿

how to deal the poblem？I can not see the answer.Anyone tell me ?

do you solve it? I still have this problem

**Comment by 0nea** [comment]
Is it the code? However, when I do not add "view all", I can successfully run the command.

---- Replied Message ----
| From | ***@***.***> |
| Date | 03/14/2024 22:47 |
| To | lucastabelini/LaneATT ***@***.***> |
| Cc | 0nea ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [lucastabelini/LaneATT] [Error Report] dfitpack.error: (1<=k && k<=5) failed for 3rd argument k: fpcurf0:k=0 (#10) |

Yes，maybe you should check every step you think important,you can use "print" to check these messages.发自我的 iPhone在 2024年3月14日，22:10，0nea ***@***.***> 写道：﻿

how to deal the poblem？I can not see the answer.Anyone tell me ?

do you solve it? I still have this problem
