### ISSUE TITLE
AttributeError: module 'lib.models' has no attribute 'LaneATT'

### ISSUE THREAD

**Issue by GreatZeZuo** [lucastabelini/LaneATT#101]
when I run " python main.py train --exp_name laneatt_r34_tusimple --cfg cfgs/laneatt_tusimple_resnet34.yml"，the program reports an error：
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 52, in main
    runner.train()
  File "/LaneATT/lib/runner.py", line 32, in train
    model = self.cfg.get_model()
  File "/LaneATT/lib/config.py", line 28, in get_model
    return getattr(models, name)(**parameters, **kwargs)
AttributeError: module 'lib.models' has no attribute 'LaneATT'

**Comment by lucastabelini** [comment]
Are you using recommended version for all dependencies? If the code has not been modified, that error should not be happening.

**Comment by GreatZeZuo** [comment]
I used&nbsp; cuda10.1 and torch1.4. Let me explain why I used pytorch1.4 : when I setup nms package ,&nbsp; the project report "RuntimeError: Error compiling objects for extension", which is the same problem like many people. After many efforts, I found maybe the nms.cpp can't be compiled well. But when I used torch1.4, the setup work successfull. I don't know if it was right.
And&nbsp; I execute the next step, then the project report the AttributeError.
Thanks for your reply.



ze之所向，心之所往

---Original---
From: "Lucas ***@***.***&gt;
Date: Tue, Mar 8, 2022 10:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lucastabelini/LaneATT] AttributeError: module 'lib.models' has no attribute 'LaneATT' (Issue #101)




 
Are you using recommended version for all dependencies? If the code has not been modified, that error should not be happening.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lucastabelini** [comment]
I don't know what could cause that error. As you can see [here](https://github.com/lucastabelini/LaneATT/blob/main/lib/models/__init__.py#L3), the `LaneATT` attribute is defined in `lib.models. It is possible that something in your environment is not set up correctly, but it would be difficult for me to say what exactly.

**Comment by GreatZeZuo** [comment]
Thank you very much for&nbsp;your attention to my problem. I re-downloaded the project and created the cuda10.2(new download) environment&nbsp; which ran successfully.&nbsp;&nbsp;
All the problems were caused&nbsp;by cuda version 10.1, which was the environment path.&nbsp;And at first I don't have administrator rights to the server. Appreciateit again.







ze之所向，心之所往

---Original---
From: "Lucas ***@***.***&gt;
Date: Thu, Mar 10, 2022 21:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lucastabelini/LaneATT] AttributeError: module 'lib.models' hasno attribute 'LaneATT' (Issue #101)




 
I don't know what could cause that error. As you can see here, the LaneATT attribute is defined in `lib.models. It is possible that something in your environment is not set up correctly, but it would be difficult for me to say what exactly.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GreatZeZuo** [comment]
I'm sorry to interrupt again. In the testing phase, the network generates one proposal for each anchor, how to get the final few predicted lane lines from so many proposals. How to use nms without GT?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lucastabelini/LaneATT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 晚上9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lucastabelini/LaneATT] AttributeError: module 'lib.models' has no attribute 'LaneATT' (Issue #101)





 
I don't know what could cause that error. As you can see here, the LaneATT attribute is defined in `lib.models. It is possible that something in your environment is not set up correctly, but it would be difficult for me to say what exactly.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lucastabelini** [comment]
I am not sure that I understand. NMS does not require GTs. It is applied [here](https://github.com/lucastabelini/LaneATT/blob/main/lib/models/laneatt.py#L108).
