### ISSUE TITLE
nms/details.cpython-38-x86_64-linux-gnu.so:udefined symbol:_ZN6caffe28....

### ISSUE THREAD

**Issue by GongDianCheng** [lucastabelini/LaneATT#103]
Thansk for sharing codes.
These days i want the model that you proposed。when i install the nms with “python setup.py install”,it works well。However，when i run the main.py ,it reports a error obout nms like:
ImportError: /home/m/anaconda3/envs/wtt/lib/python3.8/site-packages/nms-0.0.0-py3.8-linux-x86_64.egg/nms/details.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detai

I google it，some gays said that ‘s because the verison of pytorch。So ，i tried 1.7,1.8,1.10，1.11.Howeve,i got the same error like above.
I tested it on GTX3050,cuda==11.3,pytorch==1.11。 
Any suggestion will be appreciated

**Comment by lucastabelini** [comment]
Please use the same versions defined in the README.md file (for PyTorch, CUDA, Python, etc).

**Comment by GongDianCheng** [comment]
Thansk，i will try it again
