### ISSUE TITLE
the pretrained file link is disconnected

### ISSUE THREAD

**Issue by xiaominzhen** [lucastabelini/LaneATT#104]
the "https://drive.google.com/uc?id=1R638ou1AMncTCRvrkQY6I-11CPwZy23T" for pretrained model is disconnected. 
Could you please put a valid link? very thanks

**Comment by lucastabelini** [comment]
The link is working fine for me. Maybe Google Drive is blocked in your country.

**Comment by zhangzhongyuan1996** [comment]
Maybe you can upload the zip data，because we are in Asia country,we can not use the anchor data.
