### ISSUE TITLE
用自己的数据集生成anchor的预训练权重

### ISSUE THREAD

**Issue by Gooddz1** [lucastabelini/LaneATT#105]
你好，如何用自己的数据集生成anchor的预训练权重？tusimple数据集的格式

**Comment by lucastabelini** [comment]
In English, please.

**Comment by Gooddz1** [comment]
Hello, how to use your own data set to generate anchor's pre training weight? Format of tusimple dataset     It's gen_ anchor_ mask. py?

**Comment by Gooddz1** [comment]
I use gen_ anchor_ mask.py.The anchor pre training weight generated by py is only 4.71kb

**Comment by Gooddz1** [comment]
I use the anchor pre training weight generated by myself. The size is only 4.71kb. The effect after training is very poor

**Comment by lucastabelini** [comment]
Try visualizing the anchors. There might be something wrong with it.
