### ISSUE TITLE
About the fps result

### ISSUE THREAD

**Issue by 0entropy0** [lucastabelini/LaneATT#108]
Hello ， I use a 2080Ti to run the model ，but i can not reproduce the fps result in the paper . For example , using resnet 18 as  backbone ,my fps is 170, while the result in paper is 250, could you tell me is there anyting i can do to improve it ? Thanks
 here is my environment:
ubuntu 18 pytorch 1.6 cuda 10.2 cudnn7.6.5
and I use this command :
python -m utils.speed --cfg cfgs/laneatt_culane_resnet18.yml --model_path experiments/laneatt_r18_culane/models/model_0001.pt

**Comment by lucastabelini** [comment]
Try using the final trained model (e.g., `model_0015.pt`).
