### ISSUE TITLE
error: could not convert ‘torch::kFanIn’ from ‘const torch::enumtype::kFanIn’ to ‘torch::nn::init::FanModeType {aka c10::variant<torch::enumtype::kFanIn, torch::enumtype::kFanOut>}’

### ISSUE THREAD

**Issue by Kerrwy** [lucastabelini/LaneATT#11]
Installed as follow:
torch1.6-cuda10.2
torchvision0.7.0-cuda10.2
cudatoolkit==10.2
gcc==5.3

When  I run python setup.py install in nms，have error：
/home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:66:23: error: could not convert ‘torch::kFanIn’ from ‘const torch::enumtype::kFanIn’ to ‘torch::nn::init::FanModeType {aka c10::variant<torch::enumtype::kFanIn, torch::enumtype::kFanOut>}’
/home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:66:23: error: could not convert ‘torch::kLeakyReLU’ from ‘const torch::enumtype::kLeakyReLU’ to ‘torch::nn::init::NonlinearityType {aka c10::variant<torch::enumtype::kLinear, torch::enumtype::kConv1D, torch::enumtype::kConv2D, torch::enumtype::kConv3D, torch::enumtype::kConvTranspose1D, torch::enumtype::kConvTranspose2D, torch::enumtype::kConvTranspose3D, torch::enumtype::kSigmoid, torch::enumtype::kTanh, torch::enumtype::kReLU, torch::enumtype::kLeakyReLU>}’
/home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 1ul; Derived = torch::nn::Conv1dImpl]’:
/home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:62:17:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 1ul; Derived = torch::nn::Conv1dImpl]’
/home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/optim/sgd.h:48:48:   required from here
/home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:66:23: error: could not convert ‘torch::kFanIn’ from ‘const torch::enumtype::kFanIn’ to ‘torch::nn::init::FanModeType {aka c10::variant<torch::enumtype::kFanIn, torch::enumtype::kFanOut>}’
/home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:66:23: error: could not convert ‘torch::kLeakyReLU’ from ‘const torch::enumtype::kLeakyReLU’ to ‘torch::nn::init::NonlinearityType {aka c10::variant<torch::enumtype::kLinear, torch::enumtype::kConv1D, torch::enumtype::kConv2D, torch::enumtype::kConv3D, torch::enumtype::kConvTranspose1D, torch::enumtype::kConvTranspose2D, torch::enumtype::kConvTranspose3D, torch::enumtype::kSigmoid, torch::enumtype::kTanh, torch::enumtype::kReLU, torch::enumtype::kLeakyReLU>}’
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

Would you tell me how to sove it , thankyou very much!

**Comment by lucastabelini** [comment]
Not sure. It's probably something related to your environment, but it is difficult for me to reproduce the error. You could try to run the code inside a Docker container where everything is more up to date (e.g., gcc), that way even if it doesn't work it would be possible for me to investigate.

**Comment by PeiqinZhuang** [comment]
> Installed as follow: torch1.6-cuda10.2 torchvision0.7.0-cuda10.2 cudatoolkit==10.2 gcc==5.3
> 
> When I run python setup.py install in nms，have error： /home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:66:23: error: could not convert ‘torch::kFanIn’ from ‘const torch::enumtype::kFanIn’ to ‘torch::nn::init::FanModeType {aka c10::variant<torch::enumtype::kFanIn, torch::enumtype::kFanOut>}’ /home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:66:23: error: could not convert ‘torch::kLeakyReLU’ from ‘const torch::enumtype::kLeakyReLU’ to ‘torch::nn::init::NonlinearityType {aka c10::variant<torch::enumtype::kLinear, torch::enumtype::kConv1D, torch::enumtype::kConv2D, torch::enumtype::kConv3D, torch::enumtype::kConvTranspose1D, torch::enumtype::kConvTranspose2D, torch::enumtype::kConvTranspose3D, torch::enumtype::kSigmoid, torch::enumtype::kTanh, torch::enumtype::kReLU, torch::enumtype::kLeakyReLU>}’ /home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 1ul; Derived = torch::nn::Conv1dImpl]’: /home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:62:17: required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 1ul; Derived = torch::nn::Conv1dImpl]’ /home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/optim/sgd.h:48:48: required from here /home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:66:23: error: could not convert ‘torch::kFanIn’ from ‘const torch::enumtype::kFanIn’ to ‘torch::nn::init::FanModeType {aka c10::variant<torch::enumtype::kFanIn, torch::enumtype::kFanOut>}’ /home/hadoop-mtcv/.conda/envs/torch1.6/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:66:23: error: could not convert ‘torch::kLeakyReLU’ from ‘const torch::enumtype::kLeakyReLU’ to ‘torch::nn::init::NonlinearityType {aka c10::variant<torch::enumtype::kLinear, torch::enumtype::kConv1D, torch::enumtype::kConv2D, torch::enumtype::kConv3D, torch::enumtype::kConvTranspose1D, torch::enumtype::kConvTranspose2D, torch::enumtype::kConvTranspose3D, torch::enumtype::kSigmoid, torch::enumtype::kTanh, torch::enumtype::kReLU, torch::enumtype::kLeakyReLU>}’ error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
> 
> Would you tell me how to sove it , thankyou very much!

Hi, have you solved this problem yet?

**Comment by dubcyfor3** [comment]
I encountered similar problem when I use CXX standard 14, i change it to CXX standard 17 and errors disappeared

**Comment by FatemehFathiNiazi** [comment]
> I encountered similar problem when I use CXX standard 14, i change it to CXX standard 17 and errors disappeared

It solved my problem as well! Thanks!
