### ISSUE TITLE
Training on original image sizes

### ISSUE THREAD

**Issue by vincent-mayer** [lucastabelini/LaneATT#110]
Hi Lucas, thank you for this contribution. I was able to reproduce your results on TUSimple with an image size of 360x640.
If I change the image size in `cfgs/laneatt_tusimple_resnet34.yml` to the original size of 720x1280 the accuracy stays at around `50%`. Do I need to modify more from the code to train on larger images?

Thanks!

**Comment by lucastabelini** [comment]
IRRC, no, all you would have to modify are the `img_h` and `img_w` parameters in the config file. Perhaps with the increased size the anchors became too separated? That is, in the original settings, there's an anchor every 5 pixels vertically, but in the size you set there should be an anchor every 10 pixels, which can make some lanes be missed during training. You could try increasing the number of anchors generated [here](https://github.com/lucastabelini/LaneATT/blob/2f8583ba14eccba05e6779668bc3a38bc751984a/lib/models/laneatt.py#L46) and then re-generate the anchor mask using [this script](https://github.com/lucastabelini/LaneATT/blob/main/utils/gen_anchor_mask.py).

**Comment by Byronnar** [comment]
> IRRC, no, all you would have to modify are the `img_h` and `img_w` parameters in the config file. Perhaps with the increased size the anchors became too separated? That is, in the original settings, there's an anchor every 5 pixels vertically, but in the size you set there should be an anchor every 10 pixels, which can make some lanes be missed during training. You could try increasing the number of anchors generated [here](https://github.com/lucastabelini/LaneATT/blob/2f8583ba14eccba05e6779668bc3a38bc751984a/lib/models/laneatt.py#L46) and then re-generate the anchor mask using [this script](https://github.com/lucastabelini/LaneATT/blob/main/utils/gen_anchor_mask.py).

I have changed code 
```self.anchors, self.anchors_cut = self.generate_anchors(lateral_n=72, bottom_n=128)```
to
```self.anchors, self.anchors_cut = self.generate_anchors(lateral_n=144, bottom_n=256)```, 
the result are also bad, stays at around 60%. 
```{'Accuracy': 0.5184598629954783, 'FP': 0.03864059590316573, 'FN': 0.5458566108007452, 'FPS': 1000.0}```

Do I need to modify more from the code to train on larger images? @lucastabelini , Can you give me some advice?

**Comment by Byronnar** [comment]
> Hi Lucas, thank you for this contribution. I was able to reproduce your results on TUSimple with an image size of 360x640. If I change the image size in `cfgs/laneatt_tusimple_resnet34.yml` to the original size of 720x1280 the accuracy stays at around `50%`. Do I need to modify more from the code to train on larger images?
> 
> Thanks!

Hello, Have you solved this problem?
