### ISSUE TITLE
CUDA error when training on TuSimple

### ISSUE THREAD

**Issue by anir9** [lucastabelini/LaneATT#111]
Hello,
I am trying to train the model on the TuSimple dataset with the ResNet34 backbone. I keep encountering an unknown CUDA error. I am not sure what the issue is as the program is recognizing that CUDA is available and I cannot seem to find a solution to my problem. I've tried it on the other backbones and have encountered the same issue. I am using Pytorch 1.6.0 and CUDA 10.2. 

ResNet34 
![issue](https://user-images.githubusercontent.com/48391406/165631792-fdb744c9-58bf-4b01-8868-ce19c163481e.PNG)

Here is the issue with ResNet18
![image](https://user-images.githubusercontent.com/48391406/165640438-45a2c2af-abd4-4129-8f44-ff9045529abc.png)

I'd really appreciate the help!

**Comment by lucastabelini** [comment]
Have you tried to isolate the issue by running it inside a docker container? I provided a simple one [here](https://github.com/lucastabelini/LaneATT/issues/66#issuecomment-890439235) that you could try.
