### ISSUE TITLE
Question about img = (images[0].cpu().permute(1, 2, 0).numpy() * 255).astype(np.uint8)

### ISSUE THREAD

**Issue by JonasLos** [lucastabelini/LaneATT#113]
Hello, 

i have butchered your code a little bit to allow feeding the model images from a "live" camera in ROS. It's working quite well but the only thing I did not understand is the point of the line "img = (images[0].cpu().permute(1, 2, 0).numpy() * 255).astype(np.uint8)" when running the test images. It's working without running that line but just curious to understand. 

Thank you!

**Comment by lucastabelini** [comment]
This line is supposed to run when visualizing predictions. It extracts the processed image from the batch (`images[0]`, assuming there's only one image in it) and then transforms it from a tensor to a format that OpenCV can work with (`.cpu().permute(1, 2, 0).numpy() * 255).astype(np.uint8)`), i.e., 8 bit BGR image on the CPU.

**Comment by JonasLos** [comment]
Thank you! That makes sense, I am saving the image before running it through the model as a "normal" image and passing that through so that's why I didn't need it.
