### ISSUE TITLE
Issue with NMS

### ISSUE THREAD

**Issue by Wakarox** [lucastabelini/LaneATT#115]
Hello,
I have done the prerequisites and i verified all the requirements.
But in the installation, when i do my python3 setup.py install, i can't use it because i have not the right with my user account to do it.
But, when i add sudo, PyTorch is not detected. Is this normal ?

Best Regards,

**Comment by Wakarox** [comment]
I am not using conda, i do all my configuration directly on my computer

**Comment by lucastabelini** [comment]
It looks like the problem is related to your specific configuration and not related to this repository.

**Comment by Wakarox** [comment]
That's good, it works now.
I want to know if i can put my images to predict the lane. Is it possible easily with your code ?

**Comment by lucastabelini** [comment]
Please see #3 and #46.

**Comment by Wakarox** [comment]
Thanks ! :)

**Comment by Wakarox** [comment]
I have some questions, can i ask them here or i create a new issue ?

**Comment by lucastabelini** [comment]
Any way is fine by me.

**Comment by Wakarox** [comment]
Hello.
I am searching a way to put a camera input in the test set. Is it possible ?

**Comment by Wakarox** [comment]
Maybe with an Iterable dataset ?

**Comment by lucastabelini** [comment]
It's possible if you want to implement it, but with the current state of the code it is not possible.
