### ISSUE TITLE
How to Generate Video for Culane

### ISSUE THREAD

**Issue by Harry-s-Purba** [lucastabelini/LaneATT#116]
Hey, I've completed the training and testing with the Culane dataset. I was wondering if there was an option to implement the model on a video. Sort of like a demo of the model. How exactly can I do that? Thanks

**Comment by lucastabelini** [comment]
The code does not support reading the frames directly from a video. You would have to extract the frames from the video first and then run the model inference as explained [here](https://github.com/lucastabelini/LaneATT/issues/3).
