### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jajajajaja121** [lucastabelini/LaneATT#12]
I am using pytorch 1.2 to run your model, but when it comes to nms, this bug will appear, I would like to ask, how I modify the nms program, this error will disappear? thanks. by the way, this is the whole bug message:
`
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from lib.config import Config
  File "/home/xiongpan/code/LaneATT/lib/config.py", line 3, in <module>
    import lib.models as models
  File "/home/xiongpan/code/LaneATT/lib/models/__init__.py", line 1, in <module>
    from .laneatt import LaneATT
  File "/home/xiongpan/code/LaneATT/lib/models/laneatt.py", line 10, in <module>
    from nms import nms
  File "/home/xiongpan/code/LaneATT/lib/nms/src/nms/__init__.py", line 29, in <module>
    from . import details
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
`

**Comment by jajajajaja121** [comment]
I can't use 1.5 or higher version of pytorch, because after I train my model, I need to quantify it, but the tool need torch is lower than 1.2, so, I met this embarrassed situation, if you are willing to help me, I will very thank you!

**Comment by lucastabelini** [comment]
Are you sure you compiled the NMS module using PyTorch 1.2? Try removing the files generated in the build process (i.e., `rm build dist -rf` inside the `nms` directory) and then compile it again. The PyTorch version you used to compile the module has to be the same you're going to it with. Also, does your machine have a GPU and has CUDA set up correctly?

**Comment by jajajajaja121** [comment]
My cuda and GPU seems setup correctly, I have tried input import torch in command line, and there has no error. And your advice is useful!!! Thanks a lot!

**Comment by lucastabelini** [comment]
I'm closing the issue since I assume the problem has been solved.
