### ISSUE TITLE
Why extend the line to the edge of the image

### ISSUE THREAD

**Issue by AvinsWang** [lucastabelini/LaneATT#123]
Hi, 

Thanks for your great work and clean code!

There are a question, why extend the line to the edge of the image?
I noticed that calc distance of line proposal and lane line on formula(5)
> D(X_a, X_b) = ...

only calc the common valid indices, It seems do not need to extend line
to image edge. Am I missing the point? Waiting for your reply,

Thanks.

The [code](https://github.com/lucastabelini/LaneATT/blob/main/lib/datasets/lane_dataset.py):

>two_closest_points = points[:2]
>extrap = np.polyfit(two_closest_points[:, 1], two_closest_points[:, 0], deg=1)
>extrap_ys = sample_ys[sample_ys > domain_max_y]
>extrap_xs = np.polyval(extrap, extrap_ys)
>all_xs = np.hstack((extrap_xs, interp_xs))

**Comment by lucastabelini** [comment]
I can't remember exactly why it was decided to extend the lane markings, but I don't think it's necessary,
