### ISSUE TITLE
Have you write a demo to generate the inference result?

### ISSUE THREAD

**Issue by jajajajaja121** [lucastabelini/LaneATT#13]
For visualize the result, a demo maybe necessary.

**Comment by lucastabelini** [comment]
Do you mean a visualization of the predictions? If that's what you're looking for, you can use the `--view all` flag, as explained in the [README.md](https://github.com/lucastabelini/LaneATT#training--testing).

**Comment by jajajajaja121** [comment]
> Do you mean a visualization of the predictions? If that's what you're looking for, you can use the `--view all` flag, as explained in the [README.md](https://github.com/lucastabelini/LaneATT#training--testing).

Ok, thanks a lot.
