### ISSUE TITLE
How to train on original image sizes 1280*640?

### ISSUE THREAD

**Issue by Byronnar** [lucastabelini/LaneATT#139]
Hi Lucas, thank you for this contribution. I was able to reproduce your results on TUSimple with an image size of 360x640.
If I change the image size in cfgs/laneatt_tusimple_resnet34.yml to the original size of 720x1280 the accuracy stays at around 50%. 

Also I have changed code
self.anchors, self.anchors_cut = self.generate_anchors(lateral_n=72, bottom_n=128)
to
self.anchors, self.anchors_cut = self.generate_anchors(lateral_n=144, bottom_n=256),
the result are also bad, stays at around 50%.
{'Accuracy': 0.5184598629954783, 'FP': 0.03864059590316573, 'FN': 0.5458566108007452, 'FPS': 1000.0}

Do I need to modify more from the code to train on larger images? @lucastabelini , Can you give me some advice?

Thanks!

**Comment by songyonger** [comment]
Hi, have you solved the problem?
