### ISSUE TITLE
Bad results on kitti/custom datasets. How to improve them?

### ISSUE THREAD

**Issue by Rajat-Mehta** [lucastabelini/LaneATT#17]
I tried to use your pretrained model laneatt_r34_tusimple and do inference on the kitti object detection dataset (374 x 1220). As expected the results seem to be terribly bad. 
![Capture](https://user-images.githubusercontent.com/11868713/103659250-7b61c780-4f6c-11eb-88b3-44df81215091.PNG)

My question is: what are the steps that I need to follow in order to improve lane detection results on kitti or my own custom dataset?

Thanks in advance.

**Comment by lucastabelini** [comment]
You'll have to train on KITTI/your custom dataset. For that, you can either transform the annotations to a format already used in the code (e.g., CULane's format) or implement a new loader (from the [LaneDatasetLoader](https://github.com/lucastabelini/LaneATT/blob/main/lib/datasets/lane_dataset_loader.py) abstract class). If you have issues with anything in the process tell me and I'll add a section in the README.md for that.
