### ISSUE TITLE
Can your model predict curve?

### ISSUE THREAD

**Issue by jajajajaja121** [lucastabelini/LaneATT#19]
I find you just draw a line in your visualization code, but can it predict a curve?

**Comment by lucastabelini** [comment]
The model predicts a set of points that can then be interpolated. The code draws a line as an approximation. Please take a look at the paper for more details.

**Comment by jajajajaja121** [comment]
> The model predicts a set of points that can then be interpolated. The code draws a line as an approximation. Please take a look at the paper for more details.

Ok, thanks a lot!
