### ISSUE TITLE
lane_dataset.py __getitem__()  why need to try 30 times

### ISSUE THREAD

**Issue by sunpeng981712364** [lucastabelini/LaneATT#20]
Thanks for your good work. I have some confusions. why need to try 30 times? I don't know which exception is thrown.@lucastabelini 
[https://github.com/lucastabelini/LaneATT/blob/feafd0614ba3d90270f1e9f1bcb05574a5a5bff6/lib/datasets/lane_dataset.py#L275](url)https://github.com/lucastabelini/LaneATT/blob/feafd0614ba3d90270f1e9f1bcb05574a5a5bff6/lib/datasets/lane_dataset.py#L275

**Comment by sunpeng981712364** [comment]
multiple process confiction?

**Comment by lucastabelini** [comment]
There's an extremely rare (but it can happen after a number of epochs) bug where the randomly generated augmentation parameters will generate invalid annotations. This loop just tries to augment again in case that happens, else, the training session would be interrupted.

**Comment by sunpeng981712364** [comment]
ok, thanks. another issue to confirm.  Was the resnet122  backbone trained from scatch?[https://github.com/lucastabelini/LaneATT/blob/feafd0614ba3d90270f1e9f1bcb05574a5a5bff6/lib/models/laneatt.py#L382](https://github.com/lucastabelini/LaneATT/blob/feafd0614ba3d90270f1e9f1bcb05574a5a5bff6/lib/models/laneatt.py#L382)

**Comment by lucastabelini** [comment]
Yes.

**Comment by sunpeng981712364** [comment]
Do you have some ideas to detect the horizontal lanes?

**Comment by lucastabelini** [comment]
Unfortunately no.

**Comment by sunpeng981712364** [comment]
Thanks anyway.
