### ISSUE TITLE
How to know lane id  from the output prediction ?

### ISSUE THREAD

**Issue by rock2021** [lucastabelini/LaneATT#21]
Hi @lucastabelini 

Thanks for the wonderful work !!

I was trying to evaluate the model on some test images. The model predicted an array of lane points.

But how do we identify which array belongs to the specific lane id.

(Note: I found that the predicted lane array is not in any chronological order? eg: first lane array corresponds to lane id 1)

**Comment by lucastabelini** [comment]
The model predicts a set of lanes in no specific order. The order is not required by any of the evaluation metrics. If necessary, you can use a heuristic to define those IDs.
