### ISSUE TITLE
How to generate *_anchors_freq.pt files?

### ISSUE THREAD

**Issue by XiongZhongxia** [lucastabelini/LaneATT#22]
Thanks for your interesting work!

Could you please tell me how to generate filter masks files, i.e., *_anchors_freq.pt in ROOT/data/ ? 
I loaded a tusimle_anchors_freq.pt file as 'anchors_freq_path' in the code, but found the values are [102, 773, 1874, 0, 2, 0...]. Where are these values from, since they are just for masking?

**Comment by lucastabelini** [comment]
These values are the number of times the anchor was marked as positive for a ground-truth in the dataset. [Here](https://github.com/lucastabelini/LaneATT/blob/main/lib/models/laneatt.py#L50-L54), those values are used to select the anchors with the highest frequencies. This file can be generated with the [gen_anchor_mask.py](https://github.com/lucastabelini/LaneATT/blob/main/utils/gen_anchor_mask.py) script.

**Comment by XiongZhongxia** [comment]
> 
> 
> These values are the number of times the anchor was marked as positive for a ground-truth in the dataset. [Here](https://github.com/lucastabelini/LaneATT/blob/main/lib/models/laneatt.py#L50-L54), those values are used to select the anchors with the highest frequencies. This file can be generated with the [gen_anchor_mask.py](https://github.com/lucastabelini/LaneATT/blob/main/utils/gen_anchor_mask.py) script.

Thanks a lot !

**Comment by janice555** [comment]
Excuse me,how and when to generate anchor mask? What are the specific orders?
