### ISSUE TITLE
How to detect real-time image

### ISSUE THREAD

**Issue by NeilKuo** [lucastabelini/LaneATT#23]
Hi 
I very much benefited from this project.
Can this project  detect real-time images from webcam?
Thank you so much!!

**Comment by lucastabelini** [comment]
No, unfortunately.

**Comment by Wakarox** [comment]
Hello,
I want to use ROS with camera input (rosbag) with your project.
Is it possible with some modifications ?
Because i am searching a deep-learning method working with real-time, but i never found.

**Comment by ok-kewei** [comment]
> Hello, I want to use ROS with camera input (rosbag) with your project. Is it possible with some modifications ? Because i am searching a deep-learning method working with real-time, but i never found.

@Wakarox have you found one?
