### ISSUE TITLE
NMS before loss computation is necesseray?

### ISSUE THREAD

**Issue by sunpeng981712364** [lucastabelini/LaneATT#24]
https://github.com/lucastabelini/LaneATT/blob/feafd0614ba3d90270f1e9f1bcb05574a5a5bff6/lib/models/laneatt.py#L108
How about remove the NMS to let multiple anchors to predict one lane? @lucastabelini

**Comment by lucastabelini** [comment]
Without thinking too much about it right now, I think it's better to leave it as it is. I think the model has to learn with the NMS being used, as done in generic object detectors. You can give it a try though.

**Comment by sunpeng981712364** [comment]
I find that there is no nms operation in fasterrcnn in training phase. Am i in mistakes?



发自我的iPhone


------------------ Original ------------------

**Comment by sunpeng981712364** [comment]
nms only exists in the test phase to decrease the unqualified Bbox.

**Comment by lucastabelini** [comment]
The NMS operation is also applied during the training phase in Faster R-CNN.

**Comment by sunpeng981712364** [comment]
I removed NMS in the training phase and keep it in the test phase.

**Comment by sunpeng981712364** [comment]
I removed NMS in the training phase and keep it in the test phase. 
 NO  NMS:  {'Accuracy': 0.9575331211, 'FP': 0.0385933381, 'FN': 0.0266594776, 'FPS': 1000.0}
 NMS:         {'Accuracy': 0.9563509894, 'FP': 0.0350826743, 'FN': 0.0293254254, 'FPS': 1000.0}
it seems that there are no big differences.

**Comment by lucastabelini** [comment]
Interesting. I suppose the training time decreased significantly?

**Comment by sunpeng981712364** [comment]
no. it seems comparable.

**Comment by hthoai** [comment]
Hi @sunpeng981712364 ,
Could you please share with me the code with no nms in the training phase?!

**Comment by sunpeng981712364** [comment]
> Hi @sunpeng981712364 ,
> Could you please share with me the code with no nms in the training phase?!
you can comment the line, simple let keep all True.
https://github.com/lucastabelini/LaneATT/blob/c97f5731901c90b87c4b561a68a77ea893268aca/lib/models/laneatt.py#L129

**Comment by balajiiitg** [comment]
How do i use nms to have one line for one lane in inference code

**Comment by lucastabelini** [comment]
> How do i use nms to have one line for one lane in inference code

Please elaborate.
