### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by zdminging** [lucastabelini/LaneATT#25]

**Comment by lucastabelini** [comment]
In English, please.

**Comment by zdminging** [comment]
> In English, please.

Sorry for the late response, bro, I've been negligent.
First of all, congratulations on your outstanding achievements in this work and I'd like to ask for your advice.

I used and activated the conda create command to create a python 3.8 environment，Finally, follow your steps to install setup.py. Next, I started to train the model.The following error occurred：

(laneatt) root@ubuntu:/mnt/zdm/LaneATT-main# python main.py train --exp_name zdmr34 --cfg cfgs/laneatt_culane_resnet34.yml
[2021-02-01 08:56:49,254] [lib.datasets.culane] [INFO] Loading CULane annotations (cached)...
[2021-02-01 08:56:58,711] [lib.datasets.culane] [INFO] 88880 annotations loaded, with a maximum of 4 lanes in an image.
[2021-02-01 08:56:58,712] [lib.datasets.lane_dataset] [INFO] Transforming annotations to the model's target format...
[2021-02-01 08:58:19,387] [lib.datasets.lane_dataset] [INFO] Done.
  0%|                                                                                                                                                                                                                                                   | 0/15 [00:01<?, ?it/s]
Traceback (most recent call last):                                                                                                                                                                                                                                             
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 52, in main
    runner.train()
  File "/mnt/zdm/LaneATT-main/lib/runner.py", line 51, in train
    outputs = model(images, **self.cfg.get_train_parameters())
  File "/home/crc/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/zdm/LaneATT-main/lib/models/laneatt.py", line 108, in forward
    proposals_list = self.nms(reg_proposals, attention_matrix, nms_thres, nms_topk, conf_threshold)
  File "/mnt/zdm/LaneATT-main/lib/models/laneatt.py", line 129, in nms
    keep, num_to_keep, _ = nms(proposals, scores, overlap=nms_thres, top_k=nms_topk)
TypeError: 'module' object is not callable
  0%|                                                                                                                                                                                                                                                | 0/11110 [00:03<?, ?it/s]
Segmentation fault
(laneatt) root@ubuntu:/mnt/zdm/LaneATT-main# 

I'm at a loss about it. Can you answer this question? Thank you!

**Comment by lucastabelini** [comment]
It might be the same problem as #15. Are you using PyTorch 1.6 with CUDA 10.2?

**Comment by zdminging** [comment]
> It might be the same problem as #15. Are you using PyTorch 1.6 with CUDA 10.2?

Thank you for your quick reply！I just checked it, and the results are as follows：
![image](https://user-images.githubusercontent.com/57312062/106408408-5a13ce80-6479-11eb-9856-b857a39ee835.png)

I seem to have used pytorch 1.6 with CUDA 10.2.Please check if there are any problems I didn't find.I look forward to your reply，bro~

**Comment by lucastabelini** [comment]
Is the global installation of CUDA (the one in `/usr/local/cuda`) in version 10.2?

**Comment by zdminging** [comment]
> Is the global installation of CUDA (the one in `/usr/local/cuda`) in version 10.2?

Bro！Thanks for your patient reply. I find CUDA (the one in /usr/local/cuda) only has 10.0 and 10.1. I will download 10.2 under the path /usr/local/. and see if the problem can be solved.Thank you very very much!!!

**Comment by lucastabelini** [comment]
Make sure that the NMS module is compiled with CUDA 10.2. Before compiling it with 10.2, clean any previous compilation  (i.e., `rm build dist -rf` inside the nms directory).

**Comment by zdminging** [comment]
> Make sure that the NMS module is compiled with CUDA 10.2. Before compiling it with 10.2, clean any previous compilation (i.e., `rm build dist -rf` inside the nms directory).

Thank you bro!! I will try!

**Comment by zdminging** [comment]
> Make sure that the NMS module is compiled with CUDA 10.2. Before compiling it with 10.2, clean any previous compilation (i.e., `rm build dist -rf` inside the nms directory).

I'm sorry to disturb you again，bro. I downloaded cuda10.2 and the results are as follows:

![image](https://user-images.githubusercontent.com/57312062/106428430-edfa9000-64a3-11eb-9a27-c63258d44572.png)


 It seems to have used  CUDA (the one in /usr/local/cuda) in version 10.2. But there is still the original mistake. 
Can you give me some advices? I would appreciate it!!

**Comment by lucastabelini** [comment]
Sorry for the delay. I'm not sure. Did you make sure to clean any previous compilation?

**Comment by CC2226** [comment]
Hello, I also encountered this error. My pytorch and CUDA versions are correct, and any previous compilation has been cleared, but there is still this error. Can you give me some suggestions? Thank you very much.

**Comment by lucastabelini** [comment]
Did the NMS module compile correctly? You can also try using a [Dockerfile](https://github.com/lucastabelini/LaneATT/issues/66#issuecomment-890439235).

**Comment by CC2226** [comment]
> NMS 模块是否正确编译？您也可以尝试使用[Dockerfile](https://github.com/lucastabelini/LaneATT/issues/66#issuecomment-890439235)。

OK, thank you for your reply，I'll try.

**Comment by gin564319329** [comment]
> > In English, please.
> 
> Sorry for the late response, bro, I've been negligent. First of all, congratulations on your outstanding achievements in this work and I'd like to ask for your advice.
> 
> I used and activated the conda create command to create a python 3.8 environment，Finally, follow your steps to install setup.py. Next, I started to train the model.The following error occurred：
> 
> (laneatt) root@ubuntu:/mnt/zdm/LaneATT-main# python main.py train --exp_name zdmr34 --cfg cfgs/laneatt_culane_resnet34.yml [2021-02-01 08:56:49,254] [lib.datasets.culane] [INFO] Loading CULane annotations (cached)... [2021-02-01 08:56:58,711] [lib.datasets.culane] [INFO] 88880 annotations loaded, with a maximum of 4 lanes in an image. [2021-02-01 08:56:58,712] [lib.datasets.lane_dataset] [INFO] Transforming annotations to the model's target format... [2021-02-01 08:58:19,387] [lib.datasets.lane_dataset] [INFO] Done. 0%| | 0/15 [00:01<?, ?it/s] Traceback (most recent call last): File "main.py", line 59, in main() File "main.py", line 52, in main runner.train() File "/mnt/zdm/LaneATT-main/lib/runner.py", line 51, in train outputs = model(images, **self.cfg.get_train_parameters()) File "/home/crc/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl result = self.forward(*input, **kwargs) File "/mnt/zdm/LaneATT-main/lib/models/laneatt.py", line 108, in forward proposals_list = self.nms(reg_proposals, attention_matrix, nms_thres, nms_topk, conf_threshold) File "/mnt/zdm/LaneATT-main/lib/models/laneatt.py", line 129, in nms keep, num_to_keep, _ = nms(proposals, scores, overlap=nms_thres, top_k=nms_topk) TypeError: 'module' object is not callable 0%| | 0/11110 [00:03<?, ?it/s] Segmentation fault (laneatt) root@ubuntu:/mnt/zdm/LaneATT-main#
> 
> I'm at a loss about it. Can you answer this question? Thank you!

How did you solve the problem

**Comment by Yujiayi123** [comment]
try this in lanatt.py

import sys
sys.path.append('lib/nms/dist/nms-0.0.0-py3.8-linux-x86_64.egg')
import nms

keep, num_to_keep, _ = nms.nms(proposals, scores, overlap=nms_thres, top_k=nms_topk)  #line129
