### ISSUE TITLE
what is S (strip)?

### ISSUE THREAD

**Issue by seyeeet** [lucastabelini/LaneATT#29]
can you tell me in the code [here](https://github.com/lucastabelini/LaneATT/blob/main/lib/datasets/lane_dataset.py)
what `S` is, I see it is set to 72, why? is it gonna be a different number for each dataset? 
can you please verify what are `strip_size` and `self.n_strips` and what are their usages

Thanks

**Comment by lucastabelini** [comment]
In the paper, S is named N<sub>pts</sub>.

**Comment by seyeeet** [comment]
@lucastabelini can you please verify what are `strip_size` and `self.n_strips` and what are their usages

**Comment by lucastabelini** [comment]
If you divide an image in `n_strips` identical horizontal strips of size `strip_size` you'll have `n_offsets` horizontal lines that separate those strips.

**Comment by seyeeet** [comment]
Thank you
