### ISSUE TITLE
Convert to Torchscript

### ISSUE THREAD

**Issue by dkhanna511** [lucastabelini/LaneATT#30]
How can I convert the saved models into torchscript so that I can make them compatible with C++ version.

**Comment by lucastabelini** [comment]
Sorry, I have not worked with Torchscript before.

**Comment by dkhanna511** [comment]
Can you suggest some other way to use the model in C++?

**Comment by lucastabelini** [comment]
I'm not familiar with any way. Did you try [that](https://pytorch.org/tutorials/advanced/cpp_export.html#converting-to-torch-script-via-tracing)?

**Comment by dkhanna511** [comment]
Yes, I did try that. But it the complete conversion including Post Processing in C++ is still in progress. I'll update here if I get things running.

**Comment by hthoai** [comment]
Hi @dkhanna511,
Have you done converting LaneATT to TorchScript?!

**Comment by dkhanna511** [comment]
Hi @hthoai, I exported the model in Torchscript format. I loaded it in c++ and tried to run the forward function by passing an image from CULane dataset. Firstly, I'm just saving reg_proposals to the model and not the proposals_list as returned by nms function in laneatt.py. 
Therefore, the output that I'm returning is of the shape [1000, 77]. In that, I'm getting some values for column 3 and 4, and all the other columns are coming out be "nan".

**Comment by hthoai** [comment]
Hi @dkhanna511,
Thanks for your response. Did you have any trouble when exporting the model in TorchScript format?! I got some errors when scripting the model. Could I ask you some questions about the process?!

**Comment by dkhanna511** [comment]
Hi, I exported the model using tracing and didn't get any error there. But it turns out that the exported model might be wrong, because of the "nan" problem I mentioned earlier. 

I'm also trying to export the model using torch.jit.script so that I can have the complete control flow defined in the model but for that, I'm facing multiple errors. 
Please, let me know if you find something useful and are able to export the model correctly.
