### ISSUE TITLE
Test with some new images

### ISSUE THREAD

**Issue by maheshmechengg** [lucastabelini/LaneATT#31]
Hi Lucas,
Firstly Great work on Lane detection! I tried your model with exact setting & works all fine.

When i give some image generated from video, it show anchors in air and also lane are higher.
Kindly please help me with it. Also gen_video.py don't save video output somehow (did some custom code to get prediction & then stitch that as video).

![TestLane_Pred](https://user-images.githubusercontent.com/49720282/108624215-8499eb80-7469-11eb-8adc-15a9480a61ee.jpg)

**Comment by lucastabelini** [comment]
Please see this [issue](https://github.com/lucastabelini/LaneATT/issues/5#issuecomment-742944680).
