### ISSUE TITLE
Test the model on my own dataset and some thought about the model

### ISSUE THREAD

**Issue by FlowEternal** [lucastabelini/LaneATT#32]
Really Awesome work Thank you pretty much ！！！
(1) I adjust the provided pretrained model of CUlane_resnet34 on my small coarsely annotated dataset and it alreadly works pretty awesome even though the data amount is just around ~1000. With even larger amount of dataset and more detailed annotation, I suppose this model can achieve superior performance than other model!! thanks again for your genius and gorgeous work and the open access spirit of sharing your code. see the result I get after tunning the model on my own dataset.
(2) Other seemingly promising lane detection model has also been heavily tested on the actual real world dataset and I can assert that this kind of detection-based model has many advantages over other models. Model based on coarse gride and classification like "Ultra Fast Lane Detection" or based on Segmentation like the series of "SCNN, ERFNet with Self attention distillation and ERFNet with inter region affinity distillation" also do wonderful work but they all share common disadvantages of being limited by the maximal number of lane (they have to treat one lane as one specific class and thus limited by the predefined maximal class type). Also these model may encounter ambiguity when changing lanes. Besides the robust of Ultra Fast is really not so good compared to ERF and your LaneATT. 
(3) Then there is also two other types of model. One is like LaneNet that tackle the above limitation using instance segmentation but really the speed bottleneck of this model is limited by the clustering. And again another common approach is just using foreground and background segmentation (treat all lane as just one class) but then the postprocessing of seperating different lane become complex ( the connected-component analysis may not work as one expected)
(4) Actually the first detection-based lane detection paper that I read is not your LaneATT but LineCNN. When finishing this paper I immediately plan to write the code to reproduce the result. Then I contact the author for suggestion, and the author suggest me to follow your repo and says that your repo perfectly reproduce his paper, So that is why I am here. Compared with his work, your work not only gather information of boundary for lane detection but the whole region of feature map that related to rasterized anchor proposal line, which is awesome. 
(5) finally I am wondering that is there any possibility to further prompt the model by changing the backbone network from purely image-based net to someting like ConvLSTM like the paper "Robust Lane Detection from Continuous Driving Scenes Using Deep Neural Networks". again really appriciate your work!  

https://user-images.githubusercontent.com/41542584/109404742-f01d1500-79a3-11eb-89b6-0c7ecc2466ec.mp4

**Comment by lucastabelini** [comment]
Thank you for your compliments :)

> finally I am wondering that is there any possibility to further prompt the model by changing the backbone network from purely image-based net to someting like ConvLSTM like the paper "Robust Lane Detection from Continuous Driving Scenes Using Deep Neural Networks"

I can't see any intrinsic limitations neither in our method nor in ConvLSTM, so, yes, I think it is possible. I think it should not be  hard to do that, as you'll probably only have to remove their decoder. The rest should be easy to plug into LaneATT.
