### ISSUE TITLE
gen_video

### ISSUE THREAD

**Issue by janice555** [lucastabelini/LaneATT#33]
I have followed your suggestion to generate a video,but I cann't find this video anywhere,How to solve this problem？ thank you.
"First, you have to run the main script with the --save_predictions flag. This will save a predictions.pkl file with raw predictions. Then, you can run python -m utils.gen_video with the appropriate arguments."

![image](https://user-images.githubusercontent.com/59214880/110325432-4e0bc580-8052-11eb-81c8-9b601722c3fc.png)

**Comment by lucastabelini** [comment]
As shown in the picture, there seems to be an error with your OpenCV installation. Try looking for a solution to this error.

**Comment by janice555** [comment]
I have solved this problem, but I still can't find the video

**Comment by lucastabelini** [comment]
Hard to know. Perhaps there's something wrong with the permissions?

**Comment by janice555** [comment]
What permissions are you referring to?

**Comment by lucastabelini** [comment]
Linux file permissions.

**Comment by janice555** [comment]
Thank you. Let me check.There is also a problem, when I follow this command, the process is stuck, always at 0%,There won't be any problems without "--view all"
![image](https://user-images.githubusercontent.com/59214880/110348166-4eb15580-806c-11eb-851e-bb68d395e169.png)

**Comment by lucastabelini** [comment]
It's stuck at 0% because you have to press a key (when the image window is on focus) to skip to the next image.

**Comment by janice555** [comment]
Okay, thank you. It works

**Comment by janice555** [comment]
Sorry to bother you again, under which path will the video be saved?Is it the same path as prediction.pkl file

**Comment by janice555** [comment]
Now that I've changed the format of fourcc, I can generate a video

**Comment by zfnmso** [comment]
> Now that I've changed the format of fourcc, I can generate a video

Sorry to bother you, I  want to ask to you which one would you changed?why I changed it to other one,but can't get the video finally agian.

**Comment by koughua** [comment]
> > Now that I've changed the format of fourcc, I can generate a video
> 
> Sorry to bother you, I want to ask to you which one would you changed?why I changed it to other one,but can't get the video finally agian.

hello, have you solve this problem? i cant get anything too.

**Comment by naaandor** [comment]
A bit late, but on line 50 from `gen_video.py` go with:
`video = create_video(args.out, width, height + (legend.shape[0] if legend is not None else 0), args.fps)`

Note the parantheses for the height argument!
If you miss them, the height of the VideoWriter will become 0 - at least, that's what happened to me.
That's not equal to 360 (the height of a frame), and as such, nothing will be written to the file because of the dimension conflict.
