### ISSUE TITLE
problem in compiling

### ISSUE THREAD

**Issue by SurPer-Y** [lucastabelini/LaneATT#34]
It's an unparalleled job !!! When I compiled the nms model, I got this error
`/usr/include/c++/8/utility(307): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: expected a ">"`
Maybe there's something wrong with my CUDA environment, so i hope to get the nms.py to avoid this problem

**Comment by lucastabelini** [comment]
I believe there's something wrong with your CUDA environment. Are you using CUDA 10.2?
