### ISSUE TITLE
Use nms in C++

### ISSUE THREAD

**Issue by dkhanna511** [lucastabelini/LaneATT#35]
I'm trying to convert the code to c++ and I want to know how do I run the nms library that is written in C++. For now what's happening is, the code is using setup.py and some python related header file to link the nms code in laneatt.py. 

How do I directly build the c++ nms code and work on it?

**Comment by lucastabelini** [comment]
The NMS module is written in CUDA, not C++. You have to use the CUDA compiler to build it.

**Comment by tuvshu99** [comment]
> I'm trying to convert the code to c++ and I want to know how do I run the nms library that is written in C++. For now what's happening is, the code is using setup.py and some python related header file to link the nms code in laneatt.py.
> 
> How do I directly build the c++ nms code and work on it?

Hello.
Have you converted the project into c++?

**Comment by dkhanna511** [comment]
Hi @tuvshu99 you need to install libtorch first, source it in your bashrc. and then compile nms using nvcc.
