### ISSUE TITLE
train on my  own dataset

### ISSUE THREAD

**Issue by janice555** [lucastabelini/LaneATT#37]
If I want to train LaneATT on my own dataset , Do I need to get the coordinate points of the lane lines for labeling?

**Comment by lucastabelini** [comment]
Yes.

**Comment by janice555** [comment]
Thank you,Do you have any suggestions on how to get the coordinates

**Comment by lucastabelini** [comment]
You can annotate the dataset with a tool such as [Scalabel](https://www.scalabel.ai/).

**Comment by janice555** [comment]
OK, thank you very much. I'll have a try

**Comment by janice555** [comment]
Since my dataset is all straight lines, can I label only two or three coordinate points for each lane line?

**Comment by lucastabelini** [comment]
I think so.
