### ISSUE TITLE
How to draw the Figure 3. in paper?

### ISSUE THREAD

**Issue by harrylin-hyl** [lucastabelini/LaneATT#38]
The line chart in the paper is excellent!  Is it drawn with pgfplot?  Can you provide me with a latex code?
Thank you very much!

**Comment by lucastabelini** [comment]
You can download the paper's LaTeX source on arXiv. In the [abstract page](https://arxiv.org/abs/2010.12035), click on "Other formats" (on the right) and then click on "Download source".

**Comment by harrylin-hyl** [comment]
Got it! Thanks!
