### ISSUE TITLE
CULane evaluator

### ISSUE THREAD

**Issue by cfzd** [lucastabelini/LaneATT#4]
Thanks for your great work! 
I noticed you rewrite a python version CULane evaluator, can I use it in my projects (another opensource lane detection method)? Also, how about the speed compared with the original C++ version? What's the error range of this version? Thanks for your reply.

**Comment by lucastabelini** [comment]
Yes, you can use it, but please add a link pointing back to this repository if possible. The script has two ways to compute the IoU: using an image (as done by the original C++ version) and using shapes (with the shapely library). The results of the first way are very close to the official code (the errors are in the order of 0.01%, as you can see in the CULane table in this repository) and faster than the official code. The second is faster but deviates more from the original version (in the order of 0.5% I think). I can't remember right now the exact speedup, but I think the Python version is around 2-3x times faster than the C++ version using the first way (with closer results) and ~5x times faster using the second way.
