### ISSUE TITLE
image name

### ISSUE THREAD

**Issue by janice555** [lucastabelini/LaneATT#40]
When testing on my own dataset, how do I print out the original name of each predicted image while "--view all"?

**Comment by lucastabelini** [comment]
You can add a print statement [here](https://github.com/lucastabelini/LaneATT/blob/main/lib/datasets/lane_dataset.py#L272) using `item['path']`.

**Comment by janice555** [comment]
but why is more than one name printed for each predicted image?

**Comment by lucastabelini** [comment]
Because the function is called more than one time. You can just uncomment [this line](https://github.com/lucastabelini/LaneATT/blob/main/lib/datasets/lane_dataset.py#L182) too.

**Comment by janice555** [comment]
if i just uncomment this line ，no name will be printed

**Comment by lucastabelini** [comment]
Put that line outside the if statement.

**Comment by janice555** [comment]
It worked .thank you very much
