### ISSUE TITLE
train on culane

### ISSUE THREAD

**Issue by janice555** [lucastabelini/LaneATT#41]
When training with Culane dataset, the following problems will appear, but the path and shape of more than a dozen pictures can be printed out. What is the reason for this? Training with the TuSimple dataset does not present this problem

![image](https://user-images.githubusercontent.com/59214880/111974720-af479480-8b3a-11eb-8d97-b93c21847117.png)

**Comment by lucastabelini** [comment]
Hard to know. Are the paths correct?

**Comment by janice555** [comment]
The paths are right

**Comment by daeunni** [comment]
@janice555  Hi, I have same problem with u. 
How did you solve it?
