### ISSUE TITLE
Comment the case that model gives empty prediction

### ISSUE THREAD

**Issue by hthoai** [lucastabelini/LaneATT#43]
Hi there,

![image](https://user-images.githubusercontent.com/28279782/113378739-ed964c80-93a1-11eb-9ce0-0eba28468008.png)

I'm trying to do inference in C++. I see that the model mostly gives prediction for the input. Could I comment those line of codes?!

**Comment by lucastabelini** [comment]
Those two lines are for the case where no predictions are above the confidence threshold. In that case, The NMS procedure is not called. If I remember correctly that's done because the NMS module expects at least one prediction.
