### ISSUE TITLE
 the gen_anchor_mask.py script.

### ISSUE THREAD

**Issue by janice555** [lucastabelini/LaneATT#44]
when I train on my own dataset , how do I get  the number of times the anchor was marked as positive? When and how to use the gen_anchor_mask.py?  What are the specific orders?

**Comment by lucastabelini** [comment]
You use the `gen_anchor_mask.py` script before training on a dataset. It will generate a `.pt` file that you should put on the config file in the field `anchors_freq_path`. You can run the script from LaneATT's root directory like this: `python -m utils.gen_anchor_mask --output anchors_freq.pt --cfg config.yaml`.

**Comment by janice555** [comment]
Thank you very much for your reply

**Comment by harinduravin** [comment]
Hi, What will happen if I train without dataset_anchors_freq.pt for a given dataset. How useful is this file?

**Comment by lucastabelini** [comment]
Both the training and the inference will run slower, but it will work just fine. You can read more about it on the [paper](https://openaccess.thecvf.com/content/CVPR2021/papers/Tabelini_Keep_Your_Eyes_on_the_Lane_Real-Time_Attention-Guided_Lane_Detection_CVPR_2021_paper.pdf) in sections 3.8 and 4.4.
