### ISSUE TITLE
How to train own data？

### ISSUE THREAD

**Issue by JobinWeng** [lucastabelini/LaneATT#46]

**Comment by lucastabelini** [comment]
You can either transform your annotations to a format that is already used in the project (i.e., CULane, TuSimple or LLAMAS' format) or create a class to load your annotations in a custom format. For the latter, you'll have to:
1. Implement [this "abstract class"](https://github.com/lucastabelini/LaneATT/blob/main/lib/datasets/lane_dataset_loader.py).  Then, save it to the same directory (e.g., `lib/datasets/custom_loader.py`).
2. Modify [this file](https://github.com/lucastabelini/LaneATT/blob/c97f5731901c90b87c4b561a68a77ea893268aca/lib/datasets/lane_dataset.py#L41) to include your loader. That is, import your loader like the others already implemented (e.g., `import custom_loader as CustomLoader`) and then add an `if` statement to use your loader (as done for the other loaders). 
3. The `dataset` variable read in the file in step 2 comes from the config file you'll use for training/testing. Therefore, create a config file that uses your loader by setting the attributes `dataset.train.dataset` and `datasets.test.dataset` to the string you put in that `if` statement (you can use the ones I provide as a basis).

This might be a bit confusing so please let me know if you have any issues.
