### ISSUE TITLE
 performance on double solid lines prediction

### ISSUE THREAD

**Issue by janice555** [lucastabelini/LaneATT#47]
after training on a new small dataset , there is a bad performance on  double solid lines, what do you think of this phenomenon? is it due to the influence of  anchor generation?
![Uploading image.png…]()

**Comment by janice555** [comment]
![image](https://user-images.githubusercontent.com/59214880/114028877-8994ec00-98ab-11eb-9fd5-1c552a93945d.png)

**Comment by lucastabelini** [comment]
Please see #36 .
