### ISSUE TITLE
test on videos

### ISSUE THREAD

**Issue by lucky-xu-1994** [lucastabelini/LaneATT#5]
thank you for your work,  I have run it successfully。but it seems to test only on images, how can I test on a video? please help!

**Comment by lucky-xu-1994** [comment]
now I have solved it ,but another problem happeded when I test on my own data, I follwed your suggestion to modify the .yaml like this:
 test:
    type: LaneDataset
    parameters:
      S: *S
      # ---------- modified lines START here  ----------
      dataset: nolabel_dataset
      img_h:  720 # Set your test images height here
      img_w:  1280 # Set your test images width here
      root: "path/to/images" # Path to the root directory of your images
      img_ext: ".png" # The loader will load every image with extension `img_ext` inside `root`
      max_lanes: *max_lanes # You should use the same number that the model was trained with (i.e., leave it as it is)
      normalize: false
      aug_chance: 0
      augmentations:
      # ---------- modified lines END here  ----------
the problem is that if I set img_h=720,img_w=1280(the size of my own data ), it doesn't produce any result, only when I set img_h=360,img_w=640,it works, why?

**Comment by lucastabelini** [comment]
Impossible to know without more information and a way to reproduce the problem.

**Comment by lucky-xu-1994** [comment]
> Impossible to know without more information and a way to reproduce the problem.

1.   I have modified the config( experiments/laneatt_r122_culane/config.yaml) like this
# ---------- modified lines START here ----------
dataset: nolabel_dataset
img_h: 720 # my test images height 
img_w: 1280 # my test images width
root: "test" # Path to the root directory of my images
img_ext: ".jpg" # The loader will load every image with extension img_ext inside root
max_lanes: *max_lanes 
normalize: false
aug_chance: 0
augmentations:
# ---------- modified lines END here ----------

2.  run  
    python main.py test --exp_name experiments/laneatt_r122_culane/ --view all
    it doesn't produce any error but just show the original image without any detection lanes.
   olny when I set the img_h: 360 img_w: 640(in experiments/laneatt_r122_culane/config.yaml), it works.

**Comment by lucastabelini** [comment]
What images are you using to test? what resolution? Testing on a different dataset than the one used to train the model has no guarantee to work.

**Comment by lucky-xu-1994** [comment]
> What images are you using to test? what resolution? Testing on a different dataset than the one used to train the model has no guarantee to work.

I used my own images ,the resolution is 1280*720, but when I use the CUlane datasets, which resolution is 1640*590, and I set
 the  img_h: 590 img_w: 1640, it doesn't produce any error but just show the original image without any detection lanes.

**Comment by lucastabelini** [comment]
If you're testing on a set of images from a different dataset than the one used to train the model then there's no guarantee the results are going to be any useful, especially when the aspect ratio from the images are different.

**Comment by lucky-xu-1994** [comment]
> If you're testing on a set of images from a different dataset than the one used to train the model then there's no guarantee the results are going to be any useful, especially when the aspect ratio from the images are different.

ok, now I got it because the model was trained on the datasets (640x360). Thank you!

**Comment by Rajat-Mehta** [comment]
@lucky-xu-1994 are you able to get results on your high resolution images, if yes, how? Or it doesn't work on custom images at all?

**Comment by lucky-xu-1994** [comment]
> @lucky-xu-1994 are you able to get results on your high resolution images, if yes, how? Or it doesn't work on custom images at all?

yes, it did.
if you want to test on other resolution images, you'd better crop the images to the same aspect ratio( culane datasets ), and then 
resize it to 640x360。

**Comment by dkhanna511** [comment]
Hi, did you manage to test on video or just the images with different resolutions and changing its path in config.yaml?

**Comment by farouk09** [comment]
> thank you for your work, I have run it successfully。but it seems to test only on images, how can I test on a video? please help!

Hi, im trying to test it on a video but it didn't work for me, can u tell how you did it ?
