### ISSUE TITLE
How to build nms without having a machine that has a GPU device?

### ISSUE THREAD

**Issue by Ebraheem1** [lucastabelini/LaneATT#50]
Whenever I run the command:  `cd lib/nms; python setup.py install; cd -`

I get `RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at` and **how can I run it on a CUDA not-supported machine like MacBook with MacOs 11.1?**

**Comment by lucastabelini** [comment]
You can't. The NMS procedure is implemented only for CUDA GPUs.

**Comment by Ebraheem1** [comment]
Does that mean, I can't test the network without GPU?

**Comment by lucastabelini** [comment]
With the current state of the code, yes. To run the model on the CPU you would need the NMS procedure to be implemented on the CPU.

**Comment by Ebraheem1** [comment]
Thanks for the clarification
