### ISSUE TITLE
About detect the lane lines of dotted lines and solid lines

### ISSUE THREAD

**Issue by wangyushengcp3** [lucastabelini/LaneATT#51]
I want to use this code to detect the lane lines of dotted lines and solid lines. Is this feasible? What should we pay attention to? Thank you。

**Comment by lucastabelini** [comment]
The datasets used in the paper's experiments include those types of lane lines.

**Comment by wangyushengcp3** [comment]
What I mean is: I have a dataset of lane lines divided into different types. Can it be used to train models for detecting and distinguishing different lane lines

**Comment by lucastabelini** [comment]
Yes, you could use the model for that. However, the current source code only predicts 2 classes: whether the lane exists or not. To add more classes, you would have to modify the code. Here's what I would recommend:

1. Create a new layer that will predict a probability for each class in the dataset [here](https://github.com/lucastabelini/LaneATT/blob/main/lib/models/laneatt.py#L65) (e.g., `classes_layer`)
2. Use `classes_layer` to predict using the features [here](https://github.com/lucastabelini/LaneATT/blob/main/lib/models/laneatt.py#L96)
3. Add those predictions to the list of outputs (e.g., apply the NMS filter on it, as done for the outputs of regression and binary classification)

After that, you would have two classifications: the one already present in the model and the one you just added. In this way, the second one would be a conditional probability.

**Comment by wangyushengcp3** [comment]
OK, I'm going to try this method.
In addition, I have a question about why open source code does not distinguish between dotted lines and solid lines.
Is it because of the lack of relevant data sets, or the little difference between the characteristics of dotted line and solid line will lead to poor results?
Do you have any ideas？

**Comment by lucastabelini** [comment]
The lack of relevant data sets. I don't think the model will have any problem with the new classification.

**Comment by ZhouYC-X** [comment]
> OK, I'm going to try this method. In addition, I have a question about why open source code does not distinguish between dotted lines and solid lines. Is it because of the lack of relevant data sets, or the little difference between the characteristics of dotted line and solid line will lead to poor results? Do you have any ideas？

LaneATT is really an effective method. Recently I tried to add lane type prediction, and encountered similar problems. I modified the model to directly classified into no lane, solid lane and dotted lane, but the performance degrades seriously. I want to know how about the method which the author provided in this issue works.

**Comment by peng8888888** [comment]
> > 好的，我将尝试这种方法。此外，我还有一个问题，为什么开源代码不区分虚线和实线。是因为缺乏相关数据集，还是虚线和实线特性差异不大会导致效果不佳？你有什么想法吗？
> 
> LaneATT确实是一种有效的方法。最近我尝试添加车道类型预测，遇到了类似的问题。我修改了模型，直接分为无车道、实心车道和虚线车道，但性能严重下降。我想知道作者在本期中提供的方法如何工作。

Hello, could you tell me the implementation details of multi classification？
