### ISSUE TITLE
LLAMAS evaluation

### ISSUE THREAD

**Issue by raulcappy** [lucastabelini/LaneATT#53]
Hello! I am trying to reproduce the results from the paper on the LLAMAS dataset. The training phase went well, but now when i am trying to test it and i am not getting any metrics, just some empty braces " { } " as output like in the first picture.
![outputLLAMAS](https://user-images.githubusercontent.com/48680063/117571155-e6b3d580-b0d5-11eb-8b88-c3de05efeb46.png)
I looked into the code and i found out that in the llamas.py file in the eval_predictions function, there is an if statement which is telling to return " { } " if the split is "test", so when i want to test, it will never pass it. I have tried to comment the statement, like in the second picture, and to run it again.
![llamas_eval](https://user-images.githubusercontent.com/48680063/117571460-58d8ea00-b0d7-11eb-9b59-fb03e03c9c88.png)
Now i am getting this error: attributeerror: 'llamas' object has no attribute 'labels_dir'

So my question is how do i properly test llamas to get the metrics?

Thank you!

**Comment by lucastabelini** [comment]
LLAMAS' test set's annotations are not public. To evaluate the model on that set you have to submit it to the [benchmark](https://unsupervised-llamas.com/boxy/login/?next=/llamas/submission).

**Comment by raulcappy** [comment]
Okay, thank you!
