### ISSUE TITLE
Failed to build NMS code

### ISSUE THREAD

**Issue by parthdave1210** [lucastabelini/LaneATT#55]
I have CUDA 11 on my system. Is this code only compatible with CUDA 10.2? Please help me here.

**Comment by lucastabelini** [comment]
No, it is compatible with any CUDA version. The only constraint is that to reproduce the results exact results with the given pre-trained models you have to use PyTorch 1.6 with CUDA 10.2. For all other purposes (e.g., to retrain on the provided datasets or a custom one) you can use any CUDA version.

**Comment by parthdave1210** [comment]
Hi, thank you very much for replying this quick. Can you help me with the error?

**Comment by parthdave1210** [comment]
can you please help me with this error?
I am new to this and need to do it.

**Comment by lucastabelini** [comment]
What error?

**Comment by parthdave1210** [comment]
FAILED: D:/LaneATT-main/lib/nms/build/temp.win-amd64-3.8/Release/src/nms_kernel.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\Users\parth\.conda\envs\laneatt\lib\site-packages\torch\include -IC:\Users\parth\.conda\envs\laneatt\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\parth\.conda\envs\laneatt\lib\site-packages\torch\include\TH -IC:\Users\parth\.conda\envs\laneatt\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -IC:\Users\parth\.conda\envs\laneatt\include -IC:\Users\parth\.conda\envs\laneatt\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c D:\LaneATT-main\lib\nms\src\nms_kernel.cu -o D:\LaneATT-main\lib\nms\build\temp.win-amd64-3.8\Release\src/nms_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=details -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
C:/Users/parth/.conda/envs/laneatt/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(483): error: a member with an in-class initializer must be const

C:/Users/parth/.conda/envs/laneatt/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(496): error: a member with an in-class initializer must be const

C:/Users/parth/.conda/envs/laneatt/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(510): error: a member with an in-class initializer must be const

C:/Users/parth/.conda/envs/laneatt/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(523): error: a member with an in-class initializer must be const

**Comment by parthdave1210** [comment]
it does not let me insert an image so can you give me your work email so I can explain better?

**Comment by lucastabelini** [comment]
You can insert an image [like this](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests).

**Comment by parthdave1210** [comment]
![lc](https://user-images.githubusercontent.com/32506322/118750400-58ee8d80-b82d-11eb-9234-8255b48fb3d8.PNG)

**Comment by parthdave1210** [comment]
![lc2](https://user-images.githubusercontent.com/32506322/118750443-715ea800-b82d-11eb-86bd-884e7dd3da8e.PNG)

**Comment by lucastabelini** [comment]
What version of PyTorch are you using?

**Comment by parthdave1210** [comment]
pytorch 1.6.0

**Comment by lucastabelini** [comment]
Kinda difficult to say what's the problem. Did you try using CUDA 10.2?

**Comment by parthdave1210** [comment]
how can I use use CUDA 10.2

**Comment by parthdave1210** [comment]
It is not letting me install any other version of CUDA

**Comment by parthdave1210** [comment]
Is there a command to install CUDA 10.2 in this environment?

**Comment by lucastabelini** [comment]
What environment? I think PyTorch 1.6 is not compatible with CUDA 11.0.

**Comment by parthdave1210** [comment]
can I install CUDA 10.2 specifically for LANEATT env which I have to make to run this repository?

**Comment by lucastabelini** [comment]
No. You have to manually install CUDA 11.0 on your system using the instructions provided on NVIDIA's website.

**Comment by parthdave1210** [comment]
I have CUDA 11.3 on my system already
![lc3](https://user-images.githubusercontent.com/32506322/118751326-1e85f000-b82f-11eb-9b7f-2a0fb5c00a8f.PNG)

**Comment by lucastabelini** [comment]
Sorry I meant CUDA 10.2.

**Comment by parthdave1210** [comment]
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch

I am trying this right now

**Comment by parthdave1210** [comment]
![lc4](https://user-images.githubusercontent.com/32506322/118751820-fea2fc00-b82f-11eb-84db-c6672a3b3003.PNG)

**Comment by parthdave1210** [comment]
does this show this has successfully generated the NMS code?

**Comment by parthdave1210** [comment]
Hi, I just wanted to say thank you for helping me out. I successfully ran the code till the end. Sorry to bother you.

**Comment by Will-jing** [comment]
> does this show this has successfully generated the NMS code?

Hi,  I met the similar problem with you.But the environment and the version of CUDA which I install is all correct. Is there angthing wrong with the version of the Microsoft Visual Studio or the order of I install them? thank you for your help!
