### ISSUE TITLE
Can't reproduce the culane results

### ISSUE THREAD

**Issue by Smellly** [lucastabelini/LaneATT#56]
I used the pre-trained weights and `python main.py test --exp_name laneatt_r18/34/122_culane`. 
The results do not match with the paper.

laneatt_r18_culane
` {'TP': 61583, 'FP': 25973, 'FN': 31363, 'Precision': 0.7033555667230116, 'Recall': 0.6625675123189809, 'F1': 0.68223525501102481}
`
laneatt_r34_culane
` {'TP': 61954, 'FP': 28336, 'FN': 30992, 'Precision': 0.6861667958799424, 'Recall': 0.666559077313709, 'F1': 0.6762208299679102}`

 laneatt_r122_culane
` {'TP': 60938, 'FP': 25244, 'FN': 32008, 'Precision': 0.7070850061497761, 'Recall': 0.6556279990532137, 'F1': 0.6803849761064713}`

BTW tusimple results perfectly match.

**Comment by lucastabelini** [comment]
Which version of PyTorch and CUDA are you using?

**Comment by Smellly** [comment]
PyTorch: 1.6.0
cuda:10.1

**Comment by lucastabelini** [comment]
Try using CUDA 10.2. When testing with a different version than the one used to train the model the results can be different. However, the difference between your reported results and ours seems rather large. In case the discrepancy persists after you try using CUDA 10.2 I might create a Docker container that is able to reproduce our results.

**Comment by Smellly** [comment]
I notice something mismatch with other's result.
We could see that the lane num is 104886 (74298 TP + 30588 FN) from https://github.com/lucastabelini/LaneATT/issues/48#issue-860592161
However, from my result, the lane num is 92946 (61954+30992 in laneatt_r34_culane) 

Could you give me more information about whose lane num is correct if convenient?

**Comment by lucastabelini** [comment]
The correct number is 104886. The number of tested images should be 34680.

**Comment by Smellly** [comment]
Thx !
I redownloaded the CULane testset and re-evaluate the pretrained model.
r18: `TP: 72257, FP: 15299, FN: 32629, Precision: 0.8253, Recall: 0.6889, F1: 0.7509`;
r34: `TP: 74676, FP: 15281, FN: 30210, Precision: 0.8301, Recall: 0.7120, F1: 0.7665`;
r122: `TP: 73579, FP: 12603, FN: 31307, Precision: 0.8538, Recall: 0.7015, F1: 0.7702`;
