### ISSUE TITLE
nms_kernel.o:  没有哪个文件或目录

### ISSUE THREAD

**Issue by kk52099** [lucastabelini/LaneATT#57]
when i do "python setup.py install  ",  the error have happened.   "g++  : error:  /xx/LaneATT/lib/nms/build/temp.linux-x86_64-3.8/src/nms_kernel.o: 没有哪个文件或目录"
error: command'g++'  failed withexitstatus 1

**Comment by lucastabelini** [comment]
Hard to know without more information. How is your environment set up?
