### ISSUE TITLE
Running on custom dataset

### ISSUE THREAD

**Issue by jyang68sh** [lucastabelini/LaneATT#58]
Hi, I tried to run your code on a custom dataset.
However, I found the result not to be good.
I have created my custom anchor frequency .pt file. 
Does the image size matter a lot?

**Comment by lucastabelini** [comment]
> Does the image size matter a lot?

Please see Table 5 in the paper.

**Comment by jyang68sh** [comment]
@lucastabelini I think I figured out the issue. My own dataset contains only 10 images, so the anchors chosen is not good. 
I found that the anchor_features generated from the model does not contain all the lane_anchor information. Thats why my reg loss was fuked up. Thanks for your help!
