### ISSUE TITLE
how to convert .pt to onnx

### ISSUE THREAD

**Issue by xsu-yy** [lucastabelini/LaneATT#6]
hello, i have problems with converting pt to onnx,have you realized this work? 
if yes,how?
Thanks!

**Comment by lucastabelini** [comment]
I have not. I don't work with ONNX, but I think it probably isn't trivial to do that since I use custom CUDA code for the NMS module.

**Comment by BatmanofZuhandArrgh** [comment]
May I ask why use CUDA for nms? I should be able to rewrite nms module in python in its place, right?

**Comment by lucastabelini** [comment]
The NMS procedure is one of the main bottlenecks in terms of model speed. Therefore, an efficient implementation is critical. The most efficient way to implement it is using CUDA. This is why most (if not all) object detectors use a CUDA implementation for the NMS procedure. For instance, [this](https://github.com/pytorch/vision/blob/master/torchvision/csrc/ops/cuda/nms_kernel.cu) is Torchvision's NMS implementation. You can implement it in Python, but it will probably be much slower.

**Comment by yuzhobotianzhiyu** [comment]
> hello, i have problems with converting pt to onnx,have you realized this work?
> if yes,how?
> Thanks!

Are you done now? Simple deletion of the replacement operator takes away a lot of accuracy. I also want to convert to onnx and deploy it on Apollo6.0.
