### ISSUE TITLE
Failed Build NMS on Windows

### ISSUE THREAD

**Issue by ftlong6666** [lucastabelini/LaneATT#61]
Hello @lucastabelini thank you for the code. I have tried to build the NMS on windows 10 but I always failed. I exactly use the same setting as in the readme. My environment is Python 3.8, CUDA 10.2, and Pytorch 1.6.0 as in the picture.
![image](https://user-images.githubusercontent.com/56487515/121187074-413d7e80-c89a-11eb-95c2-170e71ac7cf1.png)
However I always failed with this error.
![image](https://user-images.githubusercontent.com/56487515/121187175-5e724d00-c89a-11eb-8cb9-6e79a0abbda1.png)
![image](https://user-images.githubusercontent.com/56487515/121187316-85c91a00-c89a-11eb-94f9-14910a3137b3.png)
![image](https://user-images.githubusercontent.com/56487515/121187374-94173600-c89a-11eb-847a-5d0460afc8f7.png)
How to fix this?, is there any additional setting for it? also if let say the compilation is work is it only installed in "laneatt" environment or it will be available for another environment?
-Thank you-

**Comment by ftlong6666** [comment]
After I checked carefully looks like during compilation it detect my main installed CUDA. So on my windows PC I have installed the CUDA 10.0 manually. Later on environment, I also successfully install cudatoolkit 10.2 from anaconda. However its looks like during the compilation it follow the CUDA 10.0 path. Do you know how to change the CUDA PATH during compilation to refer my CUDA 10.2?
![image](https://user-images.githubusercontent.com/56487515/121188436-b198cf80-c89b-11eb-9ac0-a4b9ea88749a.png)

**Comment by lucastabelini** [comment]
No, but you can probably

**Comment by lucastabelini** [comment]
No, but you can probably Google that.

**Comment by ftlong6666** [comment]
@lucastabelini For the NMS implementation is it necessary to use CUDA 10.2?, or is it because we install pytorch 1.6 with CUDA 10.2?, which means the CUDA version for the compilation process follows the pytorch version like for example if we have pytorch 1.4 with CUDA 10.0 it should be work in my case?

**Comment by lucastabelini** [comment]
If you want to use any of the provided pretrained models you should use CUDA 10.2, else your results would be similar to the ones reported in the paper but not exactly the same.
