### ISSUE TITLE
About FPS

### ISSUE THREAD

**Issue by xxKomorebixx** [lucastabelini/LaneATT#64]
Hello! @lucastabelini 
thanks for the paper and the code.
I have checked the log_train.txt file in the model you provided. 
Can you tell me why the FPS of the models trained by r18, r34 and r122 are all 1000? 
And why is there such a big difference between the FPS of the results given in the article and the FPS here?
Why can't FPS=1000 be the final experiment result?
I don't have much experience in this area, so if you'd like to get back to me, I'd be very grateful!

**Comment by lucastabelini** [comment]
During the training, the evaluation is computed using a batch size > 1 to make it faster. For the results reported on the paper, the evaluation uses batch size = 1 (as done in other works), since that's probably what will be used in practice. Therefore, the FPS computed during the training is not useful, so instead of computing it, it is just set to a placeholder value (1000).

**Comment by xxKomorebixx** [comment]
> 在培训期间，使用批次大小> 1 计算评估，使其更快。对于论文上报告的结果，评估使用批次大小 =1（如其他工作所述），因为这可能是实际使用的内容。因此，在培训期间计算的 FPS 没有用处，因此，它仅设置为占位符值 （1000）而不是计算它。



> During the training, the evaluation is computed using a batch size > 1 to make it faster. For the results reported on the paper, the evaluation uses batch size = 1 (as done in other works), since that's probably what will be used in practice. Therefore, the FPS computed during the training is not useful, so instead of computing it, it is just set to a placeholder value (1000).

Oh, I get it. Thank you very much for your detailed reply.So is the FPS obtained by running test.py directly the correct one?

**Comment by lucastabelini** [comment]
No, you have to use the script `utils/speed.py`.

**Comment by xxKomorebixx** [comment]
> No, you have to use the script `utils/speed.py`.
Ok, I'll get back to studying. Thank you very much! Have a good day!
