### ISSUE TITLE
A consultation on the loading of the provided .pt file

### ISSUE THREAD

**Issue by Starboy-at-earth** [lucastabelini/LaneATT#65]
Dear author:
        Due to my environ. constraints, I must rewrite the pt file loading snippet as follows:
###################################################################
        anchors_freq_path=None
        if anchors_freq_path is not None:
            anchors_mask = torch.load(anchors_freq_path).cpu()
            assert topk_anchors is not None
            ind = torch.argsort(anchors_mask, descending=True)[:topk_anchors]
            self.anchors = self.anchors[ind]
            self.anchors_cut = self.anchors_cut[ind]
###################################################################
       Could you please tell me whether the modification will deteriorate the final performance? Thank you in advance!!!

**Comment by lucastabelini** [comment]
If I understood correctly, you added this line:
```python
anchors_freq_path=None
```
By doing this, you are removing the anchor filtering step from the model, discussed in Section 3.8 of the paper. If you use this modification to test a pretrained model, it will deteriorate its performance. If you train a model with this modification, the only difference will be in terms of FPS (i.e., the model will be slower).

**Comment by Starboy-at-earth** [comment]
@lucastabelini  thamk you very much. Solved!!!

**Comment by Starboy-at-earth** [comment]
@lucastabelini  emmm... Could you please tell me without the loading step, what the final deteriorated results will look like on CULane? I am very curious about this step!!!

**Comment by lucastabelini** [comment]
If you use a pretrained model without the loading step the model's behaviour will be undefined. You should not do it.
