### ISSUE TITLE
Image Transformation

### ISSUE THREAD

**Issue by thhung** [lucastabelini/LaneATT#7]
Hi, @lucastabelini , 
I am reading your code. And I notice that in your work, even though, you used Resnet as the backbone, you didn't normalize the input images using the Resnet stats (mean, std). Would you share with me some insights/your reasons? Did you observe that normalization using these numbers did not help at all, might harm the performance, or do you have some specific reasons?  
Thanks in advance.

**Comment by lucastabelini** [comment]
If I remember correctly, it did not have much impact.
