### ISSUE TITLE
How to get my data/xx_anchors_freq.pt?

### ISSUE THREAD

**Issue by lpp0704** [lucastabelini/LaneATT#71]
I have changed the anchors_freq_path in my xx.yml file, then i run the gen_anchor_mask.py, and got the error.
<img width="698" alt="1" src="https://user-images.githubusercontent.com/45027570/129339236-7dd8a0ef-e0b1-4a72-b5a0-8293e3f6c9f4.png">

**Comment by lucastabelini** [comment]
Comment or remove the line with `anchors_freq_path:`. If the line is present, the model will try to load the file.

**Comment by lpp0704** [comment]
it's worked, thanks

**Comment by rocinant** [comment]
So, basically, the procedure is commenting the "anchors_freq_path" element in cfg file, then run the gen_anchor_mask.py script to get the top 1000 anchors. And then after the generation of new anchor file, uncomment it in the cfg file, then do the training with this cfg file. Am i right in understanding this? Thanks.
