### ISSUE TITLE
How can I output the confidence of p_0, ..., p_K?

### ISSUE THREAD

**Issue by Keiku** [lucastabelini/LaneATT#72]
Looking at the contents of the result of `experiments/laneatt_r18_tusimple/results/epoch_0015/test_predictions/test`, there is only a sequence of points `x_0, y_0, ..., x_n, y_n`. Is it possible to output the confidence of each `p_0, ..., p_K`?

**Comment by lucastabelini** [comment]
Yes, but you'll have to modify the [code](https://github.com/lucastabelini/LaneATT/blob/2f8583ba14eccba05e6779668bc3a38bc751984a/lib/models/laneatt.py#L346) for that. Those probabilities are not in the output because they are not used by the benchmark.

**Comment by Keiku** [comment]
Thank you for your reply. I will change the part you instructed.
