### ISSUE TITLE
FPS test

### ISSUE THREAD

**Issue by voldemortX** [lucastabelini/LaneATT#73]
Hi! Great code you have here! 

I just find that your FPS test script [speed.py](https://github.com/lucastabelini/LaneATT/blob/2f8583ba14eccba05e6779668bc3a38bc751984a/utils/speed.py#L52) may not be precise. Since you did not count time after all CUDA threads finish. Although this should only affect time count by `1/args.iter`, considering also the use of `time.time`, on my machine the FPS is 104.24/100.5 before/after the fix (resnet34), seeming larger than random deviations. So I'll still propose the fix in a PR for your review.

For reference:

https://pytorch.org/docs/stable/generated/torch.cuda.synchronize.html?highlight=synchro#torch.cuda.synchronize

https://www.webucator.com/article/python-clocks-explained/

> time.perf_counter() will give you the most accurate results when testing the difference between two times
> time.time() should NOT be used for comparing relative times. It’s not reliable because it’s adjustable.

command I used: `python -m utils.speed --cfg=cfgs/laneatt_tusimple_resnet34.yml`

**Comment by lucastabelini** [comment]
You are correct. However, I am not sure if I will accept pull requests into this repository since it should contain the official implementation used to obtain the results described in the paper, especially when the differences are that small. I might add a warning to the README.md explaining that, though. Thank you for your contribution.

**Comment by voldemortX** [comment]
> However, I am not sure if I will accept pull requests into this repository since it should contain the official implementation used to obtain the results described in the paper, 

Right, that is very thoughtful. Let's not merge that PR. I agree with closing it and add a ref in the readme or whatever you think is best. 

Cheers.
