### ISSUE TITLE
Image Input Format

### ISSUE THREAD

**Issue by Lllllp93** [lucastabelini/LaneATT#75]
Hi,

First of all your code is easy to get pretty good results. Just one question about the input image format. 
I found that you use cv2 to read images, but seems like images were not converted from BGR to RGB. Is there any reason?

**Comment by lucastabelini** [comment]
No reason. I probably forgot to convert. There shouldn't be much impact, though.

**Comment by Lllllp93** [comment]
> No reason. I probably forgot to convert. There shouldn't be much impact, though.

I add that RGB conversion and re-train with 18 epochs (Backbone Resnet34) on CULane, seems like the performance improves a little.
Before: 76.17 (best F1)
After: 76.55 (best F1)
But I'm not sure if this is due to different enviroments or something else, maybe you can try with that conversion.

For Your Information
