### ISSUE TITLE
/bin/sh: 1: :/usr/local/cuda:/usr/local/cuda/bin/nvcc: not found

### ISSUE THREAD

**Issue by Jad-Goh** [lucastabelini/LaneATT#78]
I meet a error as shown blow.I use GTX 3060 ,cuda 11.0 ,pytorch 1.7.0 ,python 3.8

running install
running bdist_egg
running egg_info
writing src/nms.egg-info/PKG-INFO
writing dependency_links to src/nms.egg-info/dependency_links.txt
writing top-level names to src/nms.egg-info/top_level.txt
reading manifest file 'src/nms.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/nms.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'nms.details' extension
Emitting ninja build file /home/gao/Net/LaneATT/lib/nms/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] :/usr/local/cuda:/usr/local/cuda/bin/nvcc -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/TH -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/THC -I:/usr/local/cuda:/usr/local/cuda/include -I/home/gao/anaconda3/envs/laneatt/include/python3.8 -c -c /home/gao/Net/LaneATT/lib/nms/src/nms_kernel.cu -o /home/gao/Net/LaneATT/lib/nms/build/temp.linux-x86_64-3.8/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=details -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/gao/Net/LaneATT/lib/nms/build/temp.linux-x86_64-3.8/src/nms_kernel.o 
:/usr/local/cuda:/usr/local/cuda/bin/nvcc -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/TH -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/THC -I:/usr/local/cuda:/usr/local/cuda/include -I/home/gao/anaconda3/envs/laneatt/include/python3.8 -c -c /home/gao/Net/LaneATT/lib/nms/src/nms_kernel.cu -o /home/gao/Net/LaneATT/lib/nms/build/temp.linux-x86_64-3.8/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=details -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
/bin/sh: 1: :/usr/local/cuda:/usr/local/cuda/bin/nvcc: not found
[2/2] c++ -MMD -MF /home/gao/Net/LaneATT/lib/nms/build/temp.linux-x86_64-3.8/src/nms.o.d -pthread -B /home/gao/anaconda3/envs/laneatt/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/TH -I/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/THC -I:/usr/local/cuda:/usr/local/cuda/include -I/home/gao/anaconda3/envs/laneatt/include/python3.8 -c -c /home/gao/Net/LaneATT/lib/nms/src/nms.cpp -o /home/gao/Net/LaneATT/lib/nms/build/temp.linux-x86_64-3.8/src/nms.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=details -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:12,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/gao/Net/LaneATT/lib/nms/src/nms.cpp:30:
/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
In file included from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/core/Device.h:5:0,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/gao/Net/LaneATT/lib/nms/src/nms.cpp:30:
/home/gao/Net/LaneATT/lib/nms/src/nms.cpp: In function ‘std::vector<at::Tensor> nms_forward(at::Tensor, at::Tensor, float, long unsigned int)’:
/home/gao/Net/LaneATT/lib/nms/src/nms.cpp:40:41: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                                         ^
/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:219:39: note: in definition of macro ‘C10_EXPAND_MSVC_WORKAROUND’
 #define C10_EXPAND_MSVC_WORKAROUND(x) x
                                       ^
/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:238:34: note: in expansion of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY_OR_CONST(e) C10_UNLIKELY(e)
                                  ^~~~~~~~~~~~
/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:285:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {       \
       ^~~~~~~~~~~~~~~~~~~~~
/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:447:32: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
     C10_EXPAND_MSVC_WORKAROUND(TORCH_INTERNAL_ASSERT(cond, __VA_ARGS__));     \
                                ^~~~~~~~~~~~~~~~~~~~~
/home/gao/Net/LaneATT/lib/nms/src/nms.cpp:40:23: note: in expansion of macro ‘AT_ASSERTM’
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^~~~~~~~~~
/home/gao/Net/LaneATT/lib/nms/src/nms.cpp:42:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
/home/gao/Net/LaneATT/lib/nms/src/nms.cpp:53:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(boxes);
     ^~~~~~~~~~~
In file included from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/gao/Net/LaneATT/lib/nms/src/nms.cpp:30:
/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:277:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/core/Device.h:5:0,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/gao/Net/LaneATT/lib/nms/src/nms.cpp:30:
/home/gao/Net/LaneATT/lib/nms/src/nms.cpp:40:41: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                                         ^
/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:219:39: note: in definition of macro ‘C10_EXPAND_MSVC_WORKAROUND’
 #define C10_EXPAND_MSVC_WORKAROUND(x) x
                                       ^
/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:238:34: note: in expansion of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY_OR_CONST(e) C10_UNLIKELY(e)
                                  ^~~~~~~~~~~~
/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:285:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {       \
       ^~~~~~~~~~~~~~~~~~~~~
/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:447:32: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
     C10_EXPAND_MSVC_WORKAROUND(TORCH_INTERNAL_ASSERT(cond, __VA_ARGS__));     \
                                ^~~~~~~~~~~~~~~~~~~~~
/home/gao/Net/LaneATT/lib/nms/src/nms.cpp:40:23: note: in expansion of macro ‘AT_ASSERTM’
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^~~~~~~~~~
/home/gao/Net/LaneATT/lib/nms/src/nms.cpp:42:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
/home/gao/Net/LaneATT/lib/nms/src/nms.cpp:54:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(idx);
     ^~~~~~~~~~~
In file included from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/gao/Net/LaneATT/lib/nms/src/nms.cpp:30:
/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:277:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1516, in _run_ninja_build
    subprocess.run(
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    setup(name='nms', packages=['nms'],
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 473, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/gao/anaconda3/envs/laneatt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

@ lucastabelini could you five me some suggestion,thanks!

**Comment by lucastabelini** [comment]
Check if CUDA is installed correctly. It seems the build tool was unable to find `nvcc`, the CUDA compiler.

**Comment by Jad-Goh** [comment]
> Check if CUDA is installed correctly. It seems the build tool was unable to find `nvcc`, the CUDA compiler.

Are you sure that this code is compatible with cuda 11.0 and pytorch 1.7.0 ? I refer to the official website to install the CUDA and Pytorch. Thanks for your reply.

**Comment by lucastabelini** [comment]
No. As mentioned on the README.md, the recommended CUDA version is 10.2 and PyTorch 1.6. However, I believe it should work on CUDA 11.0 and PyTorch 1.7 too. The error in the log is quite obvious: the tool was unable to find `nvcc`. Check if `/usr/local/cuda/bin/nvcc` exists. Check if your `$PATH` is set up correctly.
