### ISSUE TITLE
About train tusimple dataset batch_size

### ISSUE THREAD

**Issue by dengbin1010** [lucastabelini/LaneATT#81]
thanks for your great work!!!
i have some questions. i notice lots of model that used Tusimple trained  has small batch_size,such as 8, 4, 16, could you tell me why don`t you use more higher batch_size,such as 32 ...

**Comment by lucastabelini** [comment]
Because larger batch sizes may not fit in memory.

**Comment by dengbin1010** [comment]
> Because larger batch sizes may not fit in memory.

thanks you!
