### ISSUE TITLE
about regression loss

### ISSUE THREAD

**Issue by dengbin1010** [lucastabelini/LaneATT#82]
very great work!!!
i use tusimple dataset to train new model，but my regression loss always decrease first and then increase，batch_positive too!could you give me some advice about that? my learn_rate = 0.00035.
thanks you!!!

**Comment by lucastabelini** [comment]
Did you use the provided configs to train on TuSimple? Did the training diverge? What you described can indeed happen, but it is not necessarily bad.

**Comment by dengbin1010** [comment]
> Did you use the provided configs to train on TuSimple? Did the training diverge? What you described can indeed happen, but it is not necessarily bad.

thank you for your reply!!!.The loss is like this. i have a question about how to test diffferent type lane of CULane dataset?after i test the model, i only can see the total F1,tp and so on.
![image](https://user-images.githubusercontent.com/61703265/140016456-3b05e9f6-a75f-4d9e-bd0d-ef4fb0ab971f.png)

**Comment by lucastabelini** [comment]
Please give me more details on your issue. What exactly is the problem?
