### ISSUE TITLE
CUDA error: device-side assert triggered on Tusimple

### ISSUE THREAD

**Issue by Christin95** [lucastabelini/LaneATT#84]
Hi, 

I have some difficulties training the model on Tusimple. I get a "CUDA error: device-side assert triggered" message.

/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [123,0,0], thread: [60,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [123,0,0], thread: [61,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [123,0,0], thread: [62,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [123,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
  0%|                                                                                            | 0/100 [00:02<?, ?it/s]
Traceback (most recent call last):                                                                                       
  File "main.py", line 61, in <module>
    main()
  File "main.py", line 54, in main
    runner.train()
  File "/disk/no_backup/zl254/LaneATT/lib/runner.py", line 51, in train
    outputs = model(images, **self.cfg.get_train_parameters())
  File "/disk/no_backup/zl254/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/disk/no_backup/zl254/LaneATT/lib/models/laneatt.py", line 108, in forward
    proposals_list = self.nms(reg_proposals, attention_matrix, nms_thres, nms_topk, conf_threshold)
  File "/disk/no_backup/zl254/LaneATT/lib/models/laneatt.py", line 130, in nms
    keep = keep[:num_to_keep]
RuntimeError: CUDA error: device-side assert triggered
  0%|

Has anyone an idea how to solve this?

**Comment by lucastabelini** [comment]
Have you made any modifications to the source code? Which GPU are you using?

**Comment by Christin95** [comment]
No, I didn't. But I could solve it by using the newest Pytorch version.

**Comment by dariamuresan** [comment]
Hello, @Christin95! I have the same problem. I tried with pytorch 1.6 and also with 1.10.0 and it's still not working. The only difference I have with the env specified in the readme.md is the cuda version (I used 11.1). Could you tell me which pytorch and which cuda version you used?

**Comment by Christin95** [comment]
Hi, I installed Pytorch 1.10 with the following command: 

conda install pytorch torchvision torchaufio cudatoolkit=11.3 -c pytorch

After that it worked fine.
I hope that solves the issue!

**Comment by dariamuresan** [comment]
Thank you so much! 
Meanwhile, I tried this command: `conda install pytorch==1.6 torchvision cudatoolkit=10.2 -c pytorch` and it finally worked.
