### ISSUE TITLE
Is there any substitution operator for "img_features[self.cut_zs, self.cut_ys, self.cut_xs]"

### ISSUE THREAD

**Issue by lpp0704** [lucastabelini/LaneATT#85]
When extracting local features in the function "def cut_anchor_features(self, features):", the op "img_features[self.cut_zs, self.cut_ys, self.cut_xs]" is not supported in onnx-simple/caffe/tflite/ncnn。Could you please give me some suggestions?

**Comment by lucastabelini** [comment]
See #77.
