### ISSUE TITLE
About the values setting of args t_pos and t_neg in the function of  'match_proposals_with_targets' in lib.models.matching 

### ISSUE THREAD

**Issue by Cinderstones** [lucastabelini/LaneATT#86]
The values of args 't_pos' and 't_neg' of the function  'match_proposals_with_targets'  in module lib.models.match are set to 15. and 20. by default respectively. I’d like to know how these two values are calculated. Look forward to your reply!

**Comment by lucastabelini** [comment]
`t_pos` and `t_neg` are hyperparameters, so they are not calculated. In the paper, they are described in section 3.7, where they are named `\tau_p` and `\tau_n` instead of `t_pos` and `t_neg`, respectively.
