### ISSUE TITLE
A question about test

### ISSUE THREAD

**Issue by xing3507** [lucastabelini/LaneATT#87]
when i run     python main.py test --exp_name laneatt_r34_tusimple

it has an error :

[2021-12-03 10:09:31,500] [lib.runner] [INFO] Loading model experiments/laneatt_r34_tusimple/models/model_0100.pt
[2021-12-03 10:09:34,897] [lib.datasets.tusimple] [INFO] Loading TuSimple annotations...
[2021-12-03 10:09:35,264] [lib.datasets.tusimple] [INFO] 2782 annotations loaded, with a maximum of 5 lanes in an image.
[2021-12-03 10:09:35,265] [lib.datasets.lane_dataset] [INFO] Transforming annotations to the model's target format...
[2021-12-03 10:09:38,761] [lib.datasets.lane_dataset] [INFO] Done.
  0%|                                                                                                                                                                                    | 0/348 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 55, in main
    runner.eval(epoch=args.epoch or exp.get_last_checkpoint_epoch(), save_predictions=args.save_predictions)
  File "/media/user/date/ZXH/LaneATT-main/lib/runner.py", line 92, in eval
    output = model(images, **test_parameters)
  File "/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/user/date/ZXH/LaneATT-main/lib/models/laneatt.py", line 108, in forward
    proposals_list = self.nms(reg_proposals, attention_matrix, nms_thres, nms_topk, conf_threshold)
  File "/media/user/date/ZXH/LaneATT-main/lib/models/laneatt.py", line 129, in nms
    keep, num_to_keep, _ = nms(proposals, scores, overlap=nms_thres, top_k=nms_topk)
  File "nms.pyx", line 17, in nms.nms
TypeError: nms() got an unexpected keyword argument 'overlap'

would you please help me???

**Comment by lucastabelini** [comment]
Did any error occur during the installation of the NMS module?

**Comment by xing3507** [comment]
> Did any error occur during the installation of the NMS module?


running install
running bdist_egg
running egg_info
writing src/nms.egg-info/PKG-INFO
writing dependency_links to src/nms.egg-info/dependency_links.txt
writing top-level names to src/nms.egg-info/top_level.txt
reading manifest file 'src/nms.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/nms.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'nms.details' extension
Emitting ninja build file /media/user/date/ZXH/LaneATT-main/lib/nms/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF /media/user/date/ZXH/LaneATT-main/lib/nms/build/temp.linux-x86_64-3.8/src/nms.o.d -pthread -B /home/user/anaconda3/envs/zxh_laneatt/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include -I/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/TH -I/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/home/user/anaconda3/envs/zxh_laneatt/include/python3.8 -c -c /media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp -o /media/user/date/ZXH/LaneATT-main/lib/nms/build/temp.linux-x86_64-3.8/src/nms.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=details -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:30:
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
In file included from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/core/Device.h:5:0,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/ATen.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:30:
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp: In function ‘std::vector<at::Tensor> nms_forward(at::Tensor, at::Tensor, float, long unsigned int)’:
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:40:41: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                                         ^
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:219:39: note: in definition of macro ‘C10_EXPAND_MSVC_WORKAROUND’
 #define C10_EXPAND_MSVC_WORKAROUND(x) x
                                       ^
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:238:34: note: in expansion of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY_OR_CONST(e) C10_UNLIKELY(e)
                                  ^~~~~~~~~~~~
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:285:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {       \
       ^~~~~~~~~~~~~~~~~~~~~
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:447:32: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
     C10_EXPAND_MSVC_WORKAROUND(TORCH_INTERNAL_ASSERT(cond, __VA_ARGS__));     \
                                ^~~~~~~~~~~~~~~~~~~~~
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:40:23: note: in expansion of macro ‘AT_ASSERTM’
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^~~~~~~~~~
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:42:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:53:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(boxes);
     ^~~~~~~~~~~
In file included from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:30:
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/core/Device.h:5:0,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/ATen.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:30:
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:40:41: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                                         ^
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:219:39: note: in definition of macro ‘C10_EXPAND_MSVC_WORKAROUND’
 #define C10_EXPAND_MSVC_WORKAROUND(x) x
                                       ^
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:238:34: note: in expansion of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY_OR_CONST(e) C10_UNLIKELY(e)
                                  ^~~~~~~~~~~~
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:285:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {       \
       ^~~~~~~~~~~~~~~~~~~~~
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:447:32: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
     C10_EXPAND_MSVC_WORKAROUND(TORCH_INTERNAL_ASSERT(cond, __VA_ARGS__));     \
                                ^~~~~~~~~~~~~~~~~~~~~
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:40:23: note: in expansion of macro ‘AT_ASSERTM’
 #define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^~~~~~~~~~
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:42:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:54:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(idx);
     ^~~~~~~~~~~
In file included from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /media/user/date/ZXH/LaneATT-main/lib/nms/src/nms.cpp:30:
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
[2/2] /usr/local/cuda-10.0/bin/nvcc -I/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include -I/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/TH -I/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/home/user/anaconda3/envs/zxh_laneatt/include/python3.8 -c -c /media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu -o /media/user/date/ZXH/LaneATT-main/lib/nms/build/temp.linux-x86_64-3.8/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=details -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/record_function.h(18): warning: attribute "__visibility__" does not apply here

/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/profiler.h(97): warning: attribute "__visibility__" does not apply here

/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/profiler.h(126): warning: attribute "__visibility__" does not apply here

/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/enum.h(187): warning: statement is unreachable

/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/record_function.h(18): warning: attribute "__visibility__" does not apply here

/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/enum.h(187): warning: statement is unreachable

/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/profiler.h(97): warning: attribute "__visibility__" does not apply here

/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/profiler.h(126): warning: attribute "__visibility__" does not apply here

/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu: In lambda function:
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:171:43: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   AT_DISPATCH_FLOATING_TYPES(boxes.type(), "nms_cuda_forward", ([&] {
                                           ^
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:268:1: note: declared here
   DeprecatedTypeProperties & type() const {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:171:98: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated: passing at::DeprecatedTypeProperties to an AT_DISPATCH macro is deprecated, pass an at::ScalarType instead [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/Dispatch.h:66:1: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties& t) {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu: In lambda function:
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:171:322: warning: ‘T* at::Tensor::data() const [with T = double]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:354:1: note: declared here
   T * data() const {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:171:351: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:354:1: note: declared here
   T * data() const {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:171:381: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:354:1: note: declared here
   T * data() const {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu: In lambda function:
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:171:597: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:354:1: note: declared here
   T * data() const {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:171:626: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:354:1: note: declared here
   T * data() const {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:171:656: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:354:1: note: declared here
   T * data() const {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu: In function ‘std::vector<at::Tensor> nms_cuda_forward(at::Tensor, at::Tensor, float, long unsigned int)’:
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:183:115: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:354:1: note: declared here
   T * data() const {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:183:143: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:354:1: note: declared here
   T * data() const {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:183:171: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:354:1: note: declared here
   T * data() const {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:183:214: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:354:1: note: declared here
   T * data() const {
 ^
/media/user/date/ZXH/LaneATT-main/lib/nms/src/nms_kernel.cu:183:249: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:354:1: note: declared here
   T * data() const {
 ^
g++ -pthread -shared -B /home/user/anaconda3/envs/zxh_laneatt/compiler_compat -L/home/user/anaconda3/envs/zxh_laneatt/lib -Wl,-rpath=/home/user/anaconda3/envs/zxh_laneatt/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/user/date/ZXH/LaneATT-main/lib/nms/build/temp.linux-x86_64-3.8/src/nms.o /media/user/date/ZXH/LaneATT-main/lib/nms/build/temp.linux-x86_64-3.8/src/nms_kernel.o -L/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda-10.0/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.8/nms/details.cpython-38-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/nms
copying build/lib.linux-x86_64-3.8/nms/details.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/nms
copying build/lib.linux-x86_64-3.8/nms/__init__.py -> build/bdist.linux-x86_64/egg/nms
byte-compiling build/bdist.linux-x86_64/egg/nms/__init__.py to __init__.cpython-38.pyc
creating stub loader for nms/details.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/nms/details.py to details.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/nms.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/nms.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/nms.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/nms.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
nms.__pycache__.details.cpython-38: module references __file__
creating 'dist/nms-0.0.0-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing nms-0.0.0-py3.8-linux-x86_64.egg
removing '/home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/nms-0.0.0-py3.8-linux-x86_64.egg' (and everything under it)
creating /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/nms-0.0.0-py3.8-linux-x86_64.egg
Extracting nms-0.0.0-py3.8-linux-x86_64.egg to /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages
nms 0.0.0 is already the active version in easy-install.pth

Installed /home/user/anaconda3/envs/zxh_laneatt/lib/python3.8/site-packages/nms-0.0.0-py3.8-linux-x86_64.egg
Processing dependencies for nms==0.0.0
Finished processing dependencies for nms==0.0.0





when i run set up nms, it seems  run sucessfully,i don't know what's going on, could you please help me?

**Comment by lucastabelini** [comment]
I'm not sure. There seems to be some kind of problem with your installation. Maybe you could try using Docker. I provided an example Dockerfile [here](https://github.com/lucastabelini/LaneATT/issues/66#issuecomment-890439235).
