### ISSUE TITLE
Infer on own data

### ISSUE THREAD

**Issue by Christin95** [lucastabelini/LaneATT#89]
I was trying to apply the model on an own example image. I followed the steps you described in [https://github.com/lucastabelini/LaneATT/issues/3](url). However, I get the following result: 

python main.py test --exp_name laneatt_r34_llamas
[2021-12-06 13:38:07,376] [lib.runner] [INFO] Loading model experiments/laneatt_r34_llamas/models/model_0015.pt
Looking for image files with the pattern /disk/vanishing_data/zl254/test_folder/**/*.jpg
[2021-12-06 13:38:09,759] [lib.datasets.lane_dataset] [INFO] Transforming annotations to the model's target format...
[2021-12-06 13:38:09,759] [lib.datasets.lane_dataset] [INFO] Done.
  0%|                                                                                              | 0/1 [00:00<?, ?it/s]/disk/vanishing_data/zl254/test_folder/Grosse-Autobahn-Baustellen-zu-Ferienbeginn-auf-dem-Berliner-Suedring_reference_4_3.jpg
100%|██████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.15it/s]
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main()
  File "main.py", line 57, in main
    runner.eval(epoch=args.epoch or exp.get_last_checkpoint_epoch(), save_predictions=args.save_predictions)
  File "/disk/no_backup/zl254/LaneATT/lib/runner.py", line 106, in eval
    self.exp.eval_end_callback(dataloader.dataset.dataset, predictions, epoch)
  File "/disk/no_backup/zl254/LaneATT/lib/experiment.py", line 130, in eval_end_callback
    metrics = self.save_epoch_results(dataset, predictions, epoch_evaluated)
  File "/disk/no_backup/zl254/LaneATT/lib/experiment.py", line 137, in save_epoch_results
    predictions_dir = os.path.join(epoch_results_path, '{}_predictions'.format(dataset.split))
AttributeError: 'NoLabelDataset' object has no attribute 'split'

Can you tell me what I need to modify to make it work?

**Comment by lucastabelini** [comment]
After the model passes through every image in the dataset, it will try to save the results (metrics) to disk. Since you're using the `NoLabelDataset` class I assume you're not interested in that, only in qualitative results. Have you tried running the code with the flags `--view all`?

**Comment by Christin95** [comment]
Yes, I got the same error message

**Comment by lucastabelini** [comment]
That is expected. What are you expecting from running the code? All it can do is show a visualization of the predictions. It should have opened a window displaying them. If you want metrics, then it would be necessary to implement them for your specific dataset.

**Comment by Christin95** [comment]
Sorry, I meant I got the same error instead of a window displaying the visualization. I do not need metrics, I just wanted to see the qualitative results.

**Comment by lucastabelini** [comment]
That's odd. Are you running this script through SSH? I'm not sure what could cause the window not to show. This is the code line that should open the window: https://github.com/lucastabelini/LaneATT/blob/main/lib/runner.py#L100

**Comment by pepesouza81** [comment]
@Christin95 Did you solve the problem? I got the same error, and I have already tried to use the flags "--view all". I am trying to do the testing with my own images, and I changed the 'LaneATT/experiments/laneatt_r34_tusimple/config.yaml' as @lucastabelini proposed in issue #3, so I don't know what to do..

**Comment by ok-kewei** [comment]
@pepesouza81 what is your error message?
