### ISSUE TITLE
FPS、"normal, crowded.……"、 gen_video.py

### ISSUE THREAD

**Issue by cucula** [lucastabelini/LaneATT#9]
thank you for your great contribution. I would like to ask you the following questions.
1. How to get the Tusimple's FPS （in paper is 171）?        Why is culane the same as tusimple's fps?          How to get tusimple‘s F1 of the paper? 
I input "python main.py test-- exp_name laneatt_r18_tusimple" and the output result is: {'Accuracy': 0.9557176663, FP: 0.0356158639, FN: 0.0301042416, FPS:1000.0.  
2. Culane's "normal, crowded.……"  Where can I check the indicators? 
I typed in "python main.py test-- exp_name laneatt_r18_culane" and the output result was' TP':72243, 'FP': 15316，FN：32643，Precision: 0.8250779，Recall: 0.688776385798285，F1: 0.7507911351295176}. 
3. How to use gen_video.py? How to generate video? 
Thank you for your answer.

**Comment by lucastabelini** [comment]
1. Use `python -m utils.speed --cfg path_to_cfg.yml --model_path path_to_model.pt`. Note that the FPS metric depends heavily on your specific hardware. There's no reason for the CULane and TuSimple models to have different speeds.
2. You can either:
    1. If you have already executed the inference in the whole set (as it seems like you did), you can run the metric's script directly: `python -m utils.culane_metric --pred_dir experiments/laneatt_r18_culane/results/epoch_0015/test_predictions/ --anno_dir path/to/culane/annotations --list path/to/culane/split_list.txt --official`
    2. Change the test split in the config file to normal, crowded, etc instead of test. The splits available can be seen [here](https://github.com/lucastabelini/LaneATT/blob/feafd0614ba3d90270f1e9f1bcb05574a5a5bff6/lib/datasets/culane.py#L12). This will run the model's inference on the data in the split and then compute the metric.
3. First, you have to run the main script with the [--save_predictions flag](https://github.com/lucastabelini/LaneATT/blob/feafd0614ba3d90270f1e9f1bcb05574a5a5bff6/main.py#L19). This will save a `predictions.pkl` file with raw predictions. Then, you can run `python -m utils.gen_video` with the appropriate arguments.

**Comment by cucula** [comment]
thank you for your answer.

**Comment by FANG-MING** [comment]
the speed is influenced by the input?

**Comment by lucastabelini** [comment]
Not significantly.

**Comment by Breeze-Chou** [comment]
i follow your suggestion but i did not get the F1, how to get it 


![QQ截图20230527152220](https://github.com/lucastabelini/LaneATT/assets/46291861/f9b070fe-7a5e-44b5-ab78-f4874ec673ed)
