### ISSUE TITLE
A load persistent id instruction was encountered, but no persistent_load function was specified.

### ISSUE THREAD

**Issue by xiaoyvlongoing** [lucastabelini/LaneATT#91]
File "D:/Road/LaneATT/utils/gen_video.py", line 57, in main
predictions = np.array(pickle.load(pred_file,encoding='bytes'))
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
How to generate pkl files

**Comment by lucastabelini** [comment]
Run the test with the `--save_predictions` [flag](https://github.com/lucastabelini/LaneATT/blob/main/main.py#L19).
