### ISSUE TITLE
Ground-truth anntations interpolation

### ISSUE THREAD

**Issue by MLguy12** [lucastabelini/LaneATT#92]
Hello! 

Could you please clarify, why the ground-truth annotations are interpolated? The last point of some lanes which don't start at the corner of the image are interpolated to the edge of the image. I don't see reason for that since the network should predict the start of the lane at any point of the image. 
![pred](https://user-images.githubusercontent.com/96248464/146393541-fa5345f8-6136-4da5-8e35-b78593bbcd4e.png)

Thank you in advance.

**Comment by lucastabelini** [comment]
The model does not predict the origin of the lane. It assumes that they will always start at one of the image's boundaries, which is a valid assumption for many datasets. Therefore, if the lane does not start at one of the boundaries, it will extrapolate it to one of the boundaries. However, if necessary, you can add one more output to the model. It should not be that hard.

**Comment by MLguy12** [comment]
Thank you for your answer.
Could you please refer to the code where this extrapolation happens?

**Comment by lucastabelini** [comment]
[Here](https://github.com/lucastabelini/LaneATT/blob/main/lib/datasets/lane_dataset.py#L147-L152).

**Comment by MLguy12** [comment]
Thank you so much
