### ISSUE TITLE
the reg_loss is suddenly increace

### ISSUE THREAD

**Issue by koughua** [lucastabelini/LaneATT#93]
when i train the model, the reg_loss will suddenly increase too high, and i print it out, and re-caculate the distance, it shows 
`tensor([ 11.2221,   7.2158,  11.5707, 787.1142], device='cuda:0',
       grad_fn=<PermuteBackward>)`
the reg_proposal and reg_target is
`tensor([
        [  39.1805,  547.0710,  549.2324,  552.0231,  554.0536,  556.6360,
          559.1462,  561.5350,  563.0858,  565.2513,  567.0024,  569.5638,
          571.6778,  572.2538,  574.9627,  577.2142,  580.7488,  583.0875,
          585.7845,  588.5895,  592.3300,  595.1382,  598.8167,  600.7512,
          603.5453,  605.1068,  607.5257,  610.0900,  611.8475,  614.1852,
          615.3795,  617.2661,  617.8005,  617.8118,  619.3206,  621.3280,
          623.1306,  624.9498,  627.7559,  629.8959,  631.5656,  633.2180,
          634.7357,  636.4440,  639.1965,  640.9124,  639.2559,  642.9811,
          640.8330,  651.9212,  660.9254,  655.0208,  666.7763,  672.0029,
          671.0605,  672.1422,  675.0621,  678.0439,  680.9547,  683.8741,
          686.7943,  689.7291,  692.6240,  695.6219,  698.5938,  701.4838,
          704.3218,  707.2729,  710.2548,  713.1727,  716.0638,  719.0529,
          721.9630]], device='cuda:0', grad_fn=<SliceBackward>)`
`tensor([
        [  47.0000, 2158.9482, 2123.4419, 2087.9355, 2052.4294, 2016.9231,
         1981.4167, 1945.9105, 1910.4042, 1874.8978, 1839.3916, 1803.8853,
         1768.3790, 1732.8727, 1697.3663, 1661.8601, 1626.3538, 1590.8475,
         1555.3412, 1519.8348, 1484.3286, 1448.8223, 1413.3160, 1377.8097,
         1342.3033, 1306.7971, 1271.2908, 1235.7845, 1200.2782, 1164.7720,
         1129.2656, 1093.7593, 1058.2531, 1022.7467,  987.2404,  951.7341,
          916.2278,  880.7216,  845.2152,  809.7089,  774.2026,  738.6964,
          703.1901,  667.6838,  789.8447, 2248.3398,  632.1774,  625.3152,
          640.8330,  651.9212,  660.9254,  655.0208,  666.7763,  672.0029,
          671.0605,  672.1422,  675.0621,  678.0439,  680.9547,  683.8741,
          686.7943,  689.7291,  692.6240,  695.6219,  698.5938,  701.4838,
          704.3218,  707.2729,  710.2548,  713.1727,  716.0638,  719.0529,
          721.9630]], device='cuda:0')`
which shows that the function _match_proposals_with_targets_ do not work. but this situation only show once in an epoch, and not in every epoch. i carefully check the loss function and the match function, but did not find the problem, have you see this problem before?
![Screenshot from 2021-12-20 16-31-20](https://user-images.githubusercontent.com/76575269/146736632-bf76b01b-d034-4f43-b5dd-3457798add4a.png)

**Comment by lucastabelini** [comment]
This is probably related to a problematic annotation in the dataset. Which dataset are you using? The `reg_target` tensor has some values >  2000, which should not exist in the datasets used in this work.
