### ISSUE TITLE
multi-gpu training

### ISSUE THREAD

**Issue by Sephirex-X** [lucastabelini/LaneATT#96]
when using Dataparallel on runner.py got Error
 File "Lanatt/lib/models/laneatt.py", line 104, in forward
    reg_proposals += self.anchors
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

**Comment by lucastabelini** [comment]
I have never tried using DataParallel with LaneATT. Maybe you have to move `self.anchors` to the current GPU?

**Comment by Sephirex-X** [comment]
> I have never tried using DataParallel with LaneATT. Maybe you have to move `self.anchors` to the current GPU?

yeah I have managed to move self.anchors to current GPU, however, during the training process only one GPU was activated despite DDP or DP was set correctly.
