### ISSUE TITLE
converting LaneATT to TorchScript  Hi @dkhanna511,

### ISSUE THREAD

**Issue by hwang12345** [lucastabelini/LaneATT#98]
Hi @dkhanna511,
Thanks for your response. Did you have any trouble when exporting the model in TorchScript format?! I got some errors when scripting the model. Could I ask you some questions about the process?!

_Originally posted by @hthoai in https://github.com/lucastabelini/LaneATT/issues/30#issuecomment-801571909_

Have you done converting LaneATT to TorchScript?

**Comment by lucastabelini** [comment]
Please move this discussion to the correct issue (#77) and stop creating unnecessary new ones.
